// client-vue/src/views/AuditLogs.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import axios from 'axios'
import AdminSidebar from '../components/AdminSidebar.vue'
import ReceiptModal from '../components/ReceiptModal.vue'
import { useToast } from '../composables/useToast'

const logs = ref([])
const searchTerm = ref('')
const dateFilter = ref('')
const badgeCounts = ref({ pending: 0, ready: 0, residentApprovals: 0 })
const showReceipt = ref(false)
const receiptRequestId = ref(null)
const toast = useToast()

const fetchLogs = async () => {
  try {
    const response = await axios.get('http://localhost:5000/api/admin/audit-logs')
    logs.value = response.data
  } catch (error) {
    console.error("Failed to fetch logs", error)
  }
}

const fetchCounts = async () => {
  try {
    const [requestsRes, residentsRes] = await Promise.all([
      axios.get('http://localhost:5000/api/staff/pending-requests'),
      axios.get('http://localhost:5000/api/admin/pending-residents')
    ])
    const pending = requestsRes.data.filter(req => req.status === 'Pending').length
    const ready = requestsRes.data.filter(req => req.status === 'Ready to Print').length
    const residentApprovals = residentsRes.data.length
    badgeCounts.value = { pending, ready, residentApprovals }
  } catch (error) {
    console.error("Failed to fetch notification counts", error)
  }
}

onMounted(() => {
  fetchLogs()
  fetchCounts()
  const interval = setInterval(fetchCounts, 5000)
  return () => clearInterval(interval)
})

const filteredLogs = computed(() => {
  return logs.value.filter(log => {
    const matchesSearch = 
      log.action_type.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      log.details.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      (log.user_name && log.user_name.toLowerCase().includes(searchTerm.value.toLowerCase()))
    
    const matchesDate = dateFilter.value === '' || log.timestamp.startsWith(dateFilter.value)
    
    return matchesSearch && matchesDate
  })
})

const exportToCSV = () => {
  if (filteredLogs.value.length === 0) {
    toast.error("No logs to export.")
    return
  }
  let csvContent = "data:text/csv;charset=utf-8,"
  csvContent += "Timestamp,User,Action,Details\n"
  filteredLogs.value.forEach(log => {
    const date = new Date(log.timestamp).toLocaleString().replace(/,/g, '')
    const user = log.user_name || 'System Admin'
    const action = log.action_type
    const details = log.details.replace(/,/g, ';')
    csvContent += `${date},${user},${action},${details}\n`
  })
  const encodedUri = encodeURI(csvContent)
  const link = document.createElement("a")
  link.setAttribute("href", encodedUri)
  link.setAttribute("download", "System_Audit_Logs.csv")
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

const openReceipt = (details) => {
  const match = details.match(/Request #(\d+)/)
  if (match && match[1]) {
    receiptRequestId.value = match[1]
    showReceipt.value = true
  }
}
</script>

<template>
  <div class="flex h-screen bg-brand-gray font-sans overflow-hidden">
    
    <AdminSidebar activeMenu="Audit Logs" :badgeCounts="badgeCounts" />

    <div class="flex-1 p-8 overflow-y-auto">
      <div class="flex justify-between items-start mb-4">
        <div>
          <h1 class="text-[#0f172a] m-0 text-3xl font-bold">System Audit Logs</h1>
          <p class="text-[#64748b] mb-8 mt-1">Tracking every administrative action and system change.</p>
        </div>
        <button @click="exportToCSV" class="self-end px-5 py-2.5 bg-emerald-500 text-white rounded-lg font-bold hover:bg-emerald-600 transition whitespace-nowrap shadow-sm">
          📥 Export CSV
        </button>
      </div>

      <!-- Filters -->
      <div class="flex gap-5 mb-5 bg-white p-5 rounded-xl shadow-sm border border-gray-100">
        <div class="flex-[2]">
          <label class="block text-xs font-bold text-gray-500 mb-1">SEARCH ACTIONS OR USERS</label>
          <input 
            type="text" 
            placeholder="e.g. Privilege Change, Update, or Staff Name..." 
            v-model="searchTerm"
            class="w-full p-2.5 rounded-lg border border-gray-300 focus:outline-none focus:border-brand-blue"
          />
        </div>
        <div class="flex-1">
          <label class="block text-xs font-bold text-gray-500 mb-1">FILTER BY DATE</label>
          <input 
            type="date" 
            v-model="dateFilter"
            class="w-full p-2.5 rounded-lg border border-gray-300 focus:outline-none focus:border-brand-blue"
          />
        </div>
        <button @click="() => { searchTerm = ''; dateFilter = ''; }" class="self-end px-5 py-2.5 bg-gray-50 border border-gray-300 rounded-lg hover:bg-gray-100 transition font-medium text-gray-600">
          Reset
        </button>
      </div>

      <!-- Table -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table class="w-full text-left border-collapse table-fixed">
          <colgroup>
            <col class="w-[180px]" />
            <col class="w-[160px]" />
            <col class="w-[160px]" />
            <col />
          </colgroup>
          <thead>
            <tr class="bg-gray-50 border-b-2 border-gray-200">
              <th class="py-4 px-5 text-gray-500 text-xs font-bold">TIMESTAMP</th>
              <th class="py-4 px-5 text-gray-500 text-xs font-bold">USER</th>
              <th class="py-4 px-5 text-gray-500 text-xs font-bold">ACTION</th>
              <th class="py-4 px-5 text-gray-500 text-xs font-bold">DETAILS</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="log in filteredLogs" :key="log.log_id" class="border-b border-gray-50 hover:bg-gray-50/50">
              <td class="py-4 px-5 align-top">
                <span class="block font-semibold text-gray-700">
                  {{ new Date(log.timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }}
                </span>
                <span class="text-xs text-gray-400">
                  {{ new Date(log.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) }}
                </span>
              </td>
              <td class="py-4 px-5 align-top font-bold text-sm text-gray-800">
                {{ log.user_name || 'System Admin' }}
              </td>
              <td class="py-4 px-5 align-top">
                <span :class="[
                  'px-2.5 py-1 rounded-[4px] text-[11px] font-bold whitespace-nowrap',
                  log.action_type === 'Privilege Change' ? 'bg-amber-100 text-amber-800' :
                  log.action_type === 'Login' || log.action_type === 'Logout' ? 'bg-gray-100 text-gray-600' :
                  'bg-indigo-100 text-indigo-800'
                ]">
                  {{ log.action_type }}
                </span>
              </td>
              <td class="py-4 px-5 align-top text-gray-600 text-sm leading-relaxed break-words">
                {{ log.details }}
                <div v-if="log.details.includes('OR #')" class="mt-2.5">
                  <button 
                    @click="openReceipt(log.details)"
                    class="px-3 py-1.5 bg-blue-500 text-white border-none rounded cursor-pointer text-[11px] font-bold hover:bg-blue-600 transition"
                  >
                    👁️ View Receipt Slip
                  </button>
                </div>
              </td>
            </tr>
            <tr v-if="filteredLogs.length === 0">
              <td colspan="4" class="p-10 text-center text-gray-400 font-medium">No logs match your search criteria.</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <ReceiptModal 
      :isOpen="showReceipt"
      @close="showReceipt = false"
      :requestId="receiptRequestId"
      mode="audit"
    />
  </div>
</template>

// client/src/pages/AuditLogs.jsx
import AdminSidebar from '../components/AdminSidebar';
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';
import ReceiptModal from '../components/ReceiptModal';

export default function AuditLogs() {
  const navigate = useNavigate();
  const [logs, setLogs] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [dateFilter, setDateFilter] = useState('');
  const [badgeCounts, setBadgeCounts] = useState({ pending: 0, ready: 0, residentApprovals: 0 });
  const [showReceipt, setShowReceipt] = useState(false);
  const [receiptRequestId, setReceiptRequestId] = useState(null);

  const fetchLogs = async () => {
    try {
      const response = await axios.get('http://localhost:5000/api/admin/audit-logs');
      setLogs(response.data);
    } catch (error) { console.error("Failed to fetch logs", error); }
  };

  useEffect(() => { fetchLogs(); }, []);

  useEffect(() => {
    const fetchCounts = async () => {
      try {
        const [requestsRes, residentsRes] = await Promise.all([
            axios.get('http://localhost:5000/api/staff/pending-requests'),
            axios.get('http://localhost:5000/api/admin/pending-residents')
        ]);
        const pending = requestsRes.data.filter(req => req.status === 'Pending').length;
        const ready = requestsRes.data.filter(req => req.status === 'Ready to Print').length;
        const residentApprovals = residentsRes.data.length;
        setBadgeCounts({ pending, ready, residentApprovals });
      } catch (error) {
        console.error("Failed to fetch notification counts", error);
      }
    };
    
    fetchCounts();
    const interval = setInterval(fetchCounts, 5000);
    return () => clearInterval(interval);
  }, []);

  // Filter Logic: Search by Action, Details, User, or Date
  const filteredLogs = logs.filter(log => {
    const matchesSearch = 
      log.action_type.toLowerCase().includes(searchTerm.toLowerCase()) ||
      log.details.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (log.user_name && log.user_name.toLowerCase().includes(searchTerm.toLowerCase()));
    
    const matchesDate = dateFilter === '' || log.timestamp.startsWith(dateFilter);
    
    return matchesSearch && matchesDate;
  });

  // Export to CSV
  const exportToCSV = () => {
    if (filteredLogs.length === 0) return toast.error("No logs to export.");
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Timestamp,User,Action,Details\n";
    filteredLogs.forEach(log => {
      const date = new Date(log.timestamp).toLocaleString().replace(/,/g, '');
      const user = log.user_name || 'System Admin';
      const action = log.action_type;
      const details = log.details.replace(/,/g, ';');
      csvContent += `${date},${user},${action},${details}\n`;
    });
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "System_Audit_Logs.csv");
    document.body.appendChild(link);
    link.click();
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', fontFamily: '"Segoe UI", sans-serif', backgroundColor: '#f1f5f9' }}>
      <style>
        {`
          @keyframes pulse-red {
            0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.7); }
            70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(239, 68, 68, 0); }
            100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); }
          }
          .notification-dot {
            display: inline-flex; align-items: center; justify-content: center;
            background: #ef4444; color: white; border-radius: 50%;
            min-width: 20px; height: 20px; font-size: 11px; font-weight: bold;
            margin-left: 10px; animation: pulse-red 2s infinite;
          }
          .audit-table td { vertical-align: top; }
          .audit-table tr:hover { background: #f8fafc; }
        `}
      </style>
      
      {/* Admin Sidebar */}
      <AdminSidebar badgeCounts={badgeCounts} />

      <div style={{ flex: 1, padding: '40px', minWidth: 0 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
          <div>
            <h1 style={{ color: '#0f172a', margin: 0 }}>System Audit Logs</h1>
            <p style={{ color: '#64748b', marginBottom: '30px', marginTop: '5px' }}>Tracking every administrative action and system change.</p>
          </div>
          <button onClick={exportToCSV} style={{ alignSelf: 'flex-end', padding: '10px 20px', background: '#10b981', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', whiteSpace: 'nowrap' }}>📥 Export CSV</button>
        </div>

        {/* Filters Bar */}
        <div style={{ display: 'flex', gap: '20px', marginBottom: '20px', background: 'white', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)' }}>
          <div style={{ flex: 2 }}>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '5px' }}>SEARCH ACTIONS OR USERS</label>
            <input 
              type="text" 
              placeholder="e.g. Privilege Change, Update, or Staff Name..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1', boxSizing: 'border-box' }}
            />
          </div>
          <div style={{ flex: 1 }}>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '5px' }}>FILTER BY DATE</label>
            <input 
              type="date" 
              value={dateFilter}
              onChange={(e) => setDateFilter(e.target.value)}
              style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1', boxSizing: 'border-box' }}
            />
          </div>
          <button onClick={() => {setSearchTerm(''); setDateFilter('');}} style={{ alignSelf: 'flex-end', padding: '10px 20px', background: '#f1f5f9', border: '1px solid #cbd5e1', borderRadius: '8px', cursor: 'pointer' }}>Reset</button>
        </div>

        {/* Logs Table */}
        <div style={{ background: 'white', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
          <table className="audit-table" style={{ width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' }}>
            <colgroup>
              <col style={{ width: '180px' }} />
              <col style={{ width: '160px' }} />
              <col style={{ width: '160px' }} />
              <col /> {/* Details gets remaining space */}
            </colgroup>
            <thead>
              <tr style={{ background: '#f8fafc', borderBottom: '2px solid #e2e8f0' }}>
                <th style={{ padding: '15px 20px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>TIMESTAMP</th>
                <th style={{ padding: '15px 20px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>USER</th>
                <th style={{ padding: '15px 20px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>ACTION</th>
                <th style={{ padding: '15px 20px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>DETAILS</th>
              </tr>
            </thead>
            <tbody>
              {filteredLogs.length > 0 ? filteredLogs.map((log) => (
                <tr key={log.log_id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                  <td style={{ padding: '15px 20px', color: '#64748b', fontSize: '13px' }}>
                    <span style={{ display: 'block', fontWeight: '600', color: '#334155' }}>
                      {new Date(log.timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </span>
                    <span style={{ fontSize: '12px', color: '#94a3b8' }}>
                      {new Date(log.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </td>
                  <td style={{ padding: '15px 20px', fontWeight: 'bold', fontSize: '14px', color: '#1e293b' }}>{log.user_name || 'System Admin'}</td>
                  <td style={{ padding: '15px 20px' }}>
                    <span style={{ 
                      padding: '4px 10px', 
                      borderRadius: '4px', 
                      fontSize: '11px', 
                      fontWeight: 'bold',
                      whiteSpace: 'nowrap',
                      background: log.action_type === 'Privilege Change' ? '#fef3c7' : log.action_type === 'Login' || log.action_type === 'Logout' ? '#f1f5f9' : '#e0e7ff',
                      color: log.action_type === 'Privilege Change' ? '#92400e' : log.action_type === 'Login' || log.action_type === 'Logout' ? '#475569' : '#3730a3'
                    }}>
                      {log.action_type}
                    </span>
                  </td>
                  <td style={{ padding: '15px 20px', color: '#475569', fontSize: '14px', lineHeight: '1.6', wordBreak: 'break-word' }}>
                    {log.details}
                    {log.details.includes('OR #') && (
                      <div style={{ marginTop: '10px' }}>
                        <button 
                          onClick={() => {
                            const match = log.details.match(/Request #(\d+)/);
                            if (match && match[1]) {
                              setReceiptRequestId(match[1]);
                              setShowReceipt(true);
                            }
                          }}
                          style={{ padding: '6px 12px', background: '#3b82f6', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '11px', fontWeight: 'bold' }}
                        >
                          👁️ View Receipt Slip
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              )) : (
                <tr><td colSpan="4" style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>No logs match your search criteria.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <ReceiptModal 
        isOpen={showReceipt}
        onClose={() => setShowReceipt(false)}
        requestId={receiptRequestId}
        mode="audit"
      />
    </div>
  );
}
