// client-vue/src/views/DocumentRequest.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { useRouter, onBeforeRouteLeave } from 'vue-router'
import axios from 'axios'
import ResidentSidebar from '../components/ResidentSidebar.vue'
import ResidentBottomNav from '../components/ResidentBottomNav.vue'
import { useToast } from '../composables/useToast'

const router = useRouter()
const toast = useToast()
const availableDocs = ref([])
const availableDates = ref([])

const docType = ref('')
const purpose = ref('')
const scheduledDate = ref('')
const requirementFile = ref(null)
const requirementPreviewUrl = ref(null)
const isSubmitting = ref(false)
const fileInput = ref(null)

onBeforeRouteLeave((to, from, next) => {
  if ((docType.value || purpose.value || scheduledDate.value || requirementFile.value) && !isSubmitting.value) {
    const answer = window.confirm('You have unsaved changes. Are you sure you want to leave?')
    if (answer) {
      next()
    } else {
      next(false)
    }
  } else {
    next()
  }
})

onMounted(async () => {
  const myId = localStorage.getItem('userId')
  if (!myId) return router.push('/')

  try {
    const [docsRes, datesRes] = await Promise.all([
      axios.get('http://localhost:5000/api/requests/documents'),
      axios.get('http://localhost:5000/api/requests/available-dates')
    ])
    availableDocs.value = docsRes.data
    availableDates.value = datesRes.data
  } catch (err) {
    console.error("Error fetching data:", err)
  }
})

const selectedDocRequiresAttachment = computed(() => {
  if (!docType.value) return false
  const selectedDocObj = availableDocs.value.find(d => 
    d.doc_type_id === parseInt(docType.value, 10) || d.doc_type_id === docType.value
  )
  return selectedDocObj ? selectedDocObj.requires_attachment === 1 : false
})

const handleFileChange = (event) => {
  if (event.target.files.length > 0) {
    const file = event.target.files[0]
    
    if (file.size > 5 * 1024 * 1024) {
      toast.error("File size exceeds 5MB limit.")
      event.target.value = ''
      requirementFile.value = null
      requirementPreviewUrl.value = null
      return
    }

    requirementFile.value = file
    
    // Generate preview
    if (requirementPreviewUrl.value) {
      URL.revokeObjectURL(requirementPreviewUrl.value)
    }
    requirementPreviewUrl.value = URL.createObjectURL(file)

  } else {
    requirementFile.value = null
    requirementPreviewUrl.value = null
  }
}

const handleSubmit = async () => {
  if (isSubmitting.value) return
  
  if (!docType.value) return toast.error("Please select a document type.")
  if (!scheduledDate.value) return toast.error("Please select an appointment date.")
  
  if (selectedDocRequiresAttachment.value && !requirementFile.value) {
    return toast.error("Please upload the required document/ID.")
  }

  const myId = localStorage.getItem('userId')
  const formData = new FormData()
  
  formData.append('resident_id', myId)
  formData.append('doc_type_id', docType.value)
  formData.append('purpose', purpose.value)
  formData.append('scheduled_date', scheduledDate.value)
  
  if (requirementFile.value) {
    formData.append('requirement_file', requirementFile.value)
  }

  isSubmitting.value = true

  try {
    const response = await axios.post('http://localhost:5000/api/requests/submit', formData, {
      headers: { 'Content-Type': 'multipart/form-data' }
    })

    toast.success(`Success! Your Queue Number is: ${response.data.queue_number}`)
    // Reset state before pushing to prevent route guard block
    docType.value = ''
    purpose.value = ''
    scheduledDate.value = ''
    requirementFile.value = null
    router.push('/resident-dashboard')
  } catch (error) {
    if (error.response && error.response.status === 403) {
      toast.error(error.response.data.error || "Anti-Spam Alert: Active request already exists.")
    } else {
      toast.error("Error submitting application. Please try again.")
    }
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <div class="flex flex-col md:flex-row min-h-screen bg-brand-gray font-sans pb-[65px] md:pb-0">
    
    <ResidentSidebar activeMenu="Request Document" />

    <div class="flex-1 p-5 md:p-10 flex justify-center items-start w-full overflow-x-hidden overflow-y-auto">
      <div class="bg-white p-10 rounded-2xl shadow-sm border border-gray-200 w-full max-w-[600px] mt-5 mb-10">
        
        <h2 class="m-0 mb-2 text-gray-900 text-2xl font-bold tracking-tight">New Document Application</h2>
        <p class="text-gray-500 mb-8 mt-0 text-sm">Fill out the details below and attach the necessary requirements.</p>
        
        <form @submit.prevent="handleSubmit" class="flex flex-col gap-6">
          
          <div>
            <label class="block mb-2 text-gray-700 font-bold text-sm">Document Type</label>
            <select 
              v-model="docType" 
              class="w-full p-3 rounded-lg border border-gray-300 bg-gray-50 text-base outline-none focus:ring-2 focus:ring-brand-blue focus:bg-white transition-colors"
              required
            >
              <option value="" disabled>-- Select a Document --</option>
              <option v-for="doc in availableDocs" :key="doc.doc_type_id" :value="doc.doc_type_id">
                {{ doc.doc_name }} (Fee: ₱{{ doc.base_fee }})
              </option>
            </select>
          </div>

          <div>
            <label class="block mb-2 text-gray-700 font-bold text-sm">Select Appointment Date</label>
            <select 
              v-model="scheduledDate" 
              class="w-full p-3 rounded-lg border border-gray-300 bg-gray-50 text-base outline-none focus:ring-2 focus:ring-brand-blue focus:bg-white transition-colors"
              required
            >
              <option value="" disabled>-- Select a Date --</option>
              <option 
                v-for="(d, index) in availableDates" 
                :key="index" 
                :value="d.date" 
                :disabled="d.isFull" 
                :class="d.isFull ? 'text-red-500' : 'text-gray-900'"
              >
                {{ d.display }} {{ d.isFull ? '(QUEUE FULL)' : '' }}
              </option>
            </select>
          </div>

          <div>
            <label class="block mb-2 text-gray-700 font-bold text-sm">Purpose of Request</label>
            <input 
              type="text" 
              placeholder="e.g., Employment, School Requirement, Travel" 
              v-model="purpose" 
              required 
              class="w-full p-3 rounded-lg border border-gray-300 text-base outline-none focus:ring-2 focus:ring-brand-blue focus:bg-white transition-colors placeholder-gray-400"
            />
          </div>

          <div v-if="selectedDocRequiresAttachment" class="bg-blue-50 p-6 rounded-xl border border-blue-200">
            <label class="block mb-2 text-brand-blue font-bold text-sm">Upload Requirement (Valid ID, Cedula, etc.)</label>
            <input 
              type="file" 
              accept="image/*,.pdf" 
              @change="handleFileChange"
              required 
              class="w-full text-sm file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-brand-blue file:text-white hover:file:bg-brand-light-blue cursor-pointer"
            />
            
            <div v-if="requirementPreviewUrl" class="mt-4">
              <p class="text-xs text-gray-500 font-bold mb-2 uppercase">File Preview</p>
              <img v-if="requirementFile.type.startsWith('image/')" :src="requirementPreviewUrl" class="w-full max-h-48 object-contain rounded-lg border border-gray-300 bg-gray-100" />
              <embed v-else-if="requirementFile.type === 'application/pdf'" :src="requirementPreviewUrl" type="application/pdf" class="w-full h-48 rounded-lg border border-gray-300" />
            </div>

            <p class="text-xs text-gray-500 mt-3 mb-0 font-medium">
              Maximum file size is 5MB. Please provide a clear picture or PDF of the specific requirement needed for this document.
            </p>
          </div>

          <button 
            type="submit" 
            :disabled="isSubmitting"
            class="w-full p-4 mt-4 rounded-lg text-base font-bold text-white border-none cursor-pointer transition-colors shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
            :class="isSubmitting ? 'bg-gray-400' : 'bg-brand-blue hover:bg-brand-light-blue'"
          >
            {{ isSubmitting ? 'Submitting... Please Wait' : 'Submit Application' }}
          </button>

        </form>

      </div>
    </div>

    <ResidentBottomNav />
  </div>
</template>

// client/src/pages/DocumentRequest.jsx
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import ResidentBottomNav from '../components/ResidentBottomNav';

export default function DocumentRequest() {
  const navigate = useNavigate();
  const [availableDocs, setAvailableDocs] = useState([]);
  const [availableDates, setAvailableDates] = useState([]);
  
  // State variables to hold the form data
  const [docType, setDocType] = useState('');
  const [purpose, setPurpose] = useState('');
  const [scheduledDate, setScheduledDate] = useState('');
  const [requirementFile, setRequirementFile] = useState(null);

  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    // Check if logged in
    const myId = localStorage.getItem('userId');
    if (!myId) return navigate('/');

    // Fetch the EXACT list of active documents using the Resident route
    const fetchDocs = async () => {
      try {
        const [docsRes, datesRes] = await Promise.all([
          axios.get('http://localhost:5000/api/requests/documents'),
          axios.get('http://localhost:5000/api/requests/available-dates')
        ]);
        setAvailableDocs(docsRes.data);
        setAvailableDates(datesRes.data);
      } catch (err) {
        console.error("Error fetching data:", err);
      }
    };

    fetchDocs();
  }, [navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isSubmitting) return; // Prevent double clicks
    
    if (!docType) return toast.error("Please select a document type.");
    if (!scheduledDate) return toast.error("Please select an appointment date.");
    
    // Find the selected document object
    const selectedDocObj = availableDocs.find(d => d.doc_type_id === parseInt(docType, 10) || d.doc_type_id === docType);
    const requiresAttachment = selectedDocObj ? selectedDocObj.requires_attachment === 1 : false;

    if (requiresAttachment && !requirementFile) return toast.error("Please upload the required document/ID.");

    const myId = localStorage.getItem('userId');
    
    // Because we are sending a FILE, we MUST use FormData
    const formData = new FormData();
    formData.append('resident_id', myId);
    formData.append('doc_type_id', docType);
    formData.append('purpose', purpose);
    formData.append('scheduled_date', scheduledDate);
    formData.append('requirement_file', requirementFile);

    setIsSubmitting(true);

    try {
      const response = await axios.post('http://localhost:5000/api/requests/submit', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      toast.success(`Success! Your Queue Number is: ${response.data.queue_number}`);
      navigate('/resident-dashboard');
      
    } catch (error) {
      if (error.response && error.response.status === 403) {
        toast.error(error.response.data.error || "Anti-Spam Alert: Active request already exists.");
      } else {
        toast.error("Error submitting application. Please try again.");
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleLogout = () => {
    localStorage.clear();
    navigate('/');
  };

  return (
    <div className="flex flex-col md:flex-row min-h-screen bg-[#f4f7f6] font-sans pb-[65px] md:pb-0">
      
      {/* Sidebar */}
      <div className="hidden md:flex flex-col w-[260px] bg-[#1e3a8a] text-white p-[30px_20px] sticky top-0 h-screen overflow-y-auto">
        <h2 style={{ fontSize: '20px', margin: '0 0 40px 0', borderBottom: '1px solid #3b82f6', paddingBottom: '15px' }}>🏛️ Brgy. Fortune</h2>
        <div style={{ flex: 1 }}>
          <p onClick={() => navigate('/resident-dashboard')} className="transition-all duration-300 hover:translate-x-2 hover:bg-[#2563eb] hover:text-white" style={{ padding: '8px 16px', borderRadius: '8px', margin: '15px 0', cursor: 'pointer', color: '#93c5fd' }}>📄 My Dashboard</p>
          <p className="transition-all duration-300 hover:translate-x-2 hover:bg-[#2563eb] hover:text-white" style={{ padding: '8px 16px', borderRadius: '8px', margin: '15px 0', cursor: 'pointer', fontWeight: 'bold' }}>➕ Request Document</p>
          <p onClick={() => navigate('/profile')} className="transition-all duration-300 hover:translate-x-2 hover:bg-[#2563eb] hover:text-white" style={{ padding: '8px 16px', borderRadius: '8px', margin: '15px 0', cursor: 'pointer', color: '#93c5fd' }}>👤 Profile Settings</p>
        </div>
        <button onClick={handleLogout} className="transition-all duration-300 bg-transparent text-[#fca5a5] hover:bg-[#ef4444] hover:text-white hover:border-[#ef4444]" style={{ padding: '10px', border: '1px solid #fca5a5', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>Logout</button>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 p-5 md:p-[40px] flex justify-center items-start w-full overflow-x-hidden">
        <div style={{ background: 'white', padding: '40px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', w: '100%', maxWidth: '600px', marginTop: '20px' }}>
          
          <h2 style={{ margin: '0 0 10px 0', color: '#1f2937' }}>New Document Application</h2>
          <p style={{ color: '#6b7280', marginBottom: '30px', fontSize: '14px' }}>Fill out the details below and attach the necessary requirements.</p>
          
          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            
            {/* Dynamic Dropdown tied to Database */}
            <div>
              <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '500' }}>Document Type</label>
              <select 
                value={docType} 
                onChange={(e) => setDocType(e.target.value)} 
                style={{ width: '100%', padding: '12px', borderRadius: '6px', border: '1px solid #cbd5e1', fontSize: '15px', backgroundColor: '#f8fafc' }}
                required
              >
                <option value="" disabled>-- Select a Document --</option>
                {availableDocs.map((doc) => (
                  <option key={doc.doc_type_id} value={doc.doc_type_id}>
                    {/* HERE IS THE PESO SIGN RESTORED! */}
                    {doc.doc_name} (Fee: ₱{doc.base_fee})
                  </option>
                ))}
              </select>
            </div>

            {/* Appointment Date Dropdown */}
            <div>
              <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '500' }}>Select Appointment Date</label>
              <select 
                value={scheduledDate} 
                onChange={(e) => setScheduledDate(e.target.value)} 
                style={{ width: '100%', padding: '12px', borderRadius: '6px', border: '1px solid #cbd5e1', fontSize: '15px', backgroundColor: '#f8fafc' }}
                required
              >
                <option value="" disabled>-- Select a Date --</option>
                {availableDates.map((d, index) => (
                  <option key={index} value={d.date} disabled={d.isFull} style={{ color: d.isFull ? '#ef4444' : '#1e293b' }}>
                    {d.display} {d.isFull ? '(QUEUE FULL)' : ''}
                  </option>
                ))}
              </select>
            </div>

            {/* Purpose Textbox */}
            <div>
              <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '500' }}>Purpose of Request</label>
              <input 
                type="text" 
                placeholder="e.g., Employment, School Requirement, Travel" 
                value={purpose} 
                onChange={(e) => setPurpose(e.target.value)} 
                required 
                style={{ width: '100%', padding: '12px', borderRadius: '6px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box' }}
              />
            </div>

            {/* Conditionally Render File Upload for Requirements */}
            {(() => {
              const selectedDocObj = availableDocs.find(d => d.doc_type_id === parseInt(docType, 10) || d.doc_type_id === docType);
              if (selectedDocObj && selectedDocObj.requires_attachment === 1) {
                return (
                  <div style={{ background: '#f8fafc', padding: '20px', borderRadius: '8px', border: '1px dashed #cbd5e1' }}>
                    <label style={{ display: 'block', marginBottom: '8px', color: '#1e3a8a', fontWeight: '500' }}>Upload Requirement (Valid ID, Cedula, etc.)</label>
                    <input 
                      type="file" 
                      accept="image/*,.pdf" 
                      onChange={(e) => setRequirementFile(e.target.files[0])} 
                      required 
                      style={{ width: '100%', fontSize: '14px' }}
                    />
                    <p style={{ fontSize: '12px', color: '#64748b', marginTop: '10px', marginBottom: 0 }}>
                      Please provide a clear picture or PDF of the specific requirement needed for this document.
                    </p>
                  </div>
                );
              }
              return null;
            })()}

            <button 
              type="submit" 
              disabled={isSubmitting}
              style={{ 
                width: '100%', 
                padding: '14px', 
                background: isSubmitting ? '#94a3b8' : '#2563eb', 
                color: 'white', 
                border: 'none', 
                borderRadius: '6px', 
                fontSize: '16px', 
                fontWeight: '600', 
                cursor: isSubmitting ? 'not-allowed' : 'pointer', 
                marginTop: '10px' 
              }}
            >
              {isSubmitting ? 'Submitting... Please Wait' : 'Submit Application'}
            </button>
          </form>

        </div>
      </div>

      {/* Mobile Bottom Navigation */}
      <ResidentBottomNav />
    </div>
  );
}
