// client-vue/src/views/ResidentDashboard.vue
<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
import ResidentSidebar from '../components/ResidentSidebar.vue'
import ResidentBottomNav from '../components/ResidentBottomNav.vue'
import ConfirmModal from '../components/Modals/ConfirmModal.vue'
import { useToast } from '../composables/useToast'

const router = useRouter()
const toast = useToast()

const history = ref([])
let interval = null

const isConfirmModalOpen = ref(false)
const requestToCancel = ref(null)

const getDisplayStatus = (dbStatus, orNumber) => {
  if (!dbStatus || dbStatus === 'undefined') return 'Pending'
  if (dbStatus === 'Waiting for Printing') return 'Waiting for Printing'
  if (dbStatus === 'Ready for Pickup') {
    return orNumber ? 'Ready for Pickup (Paid)' : 'Ready for Pickup (Unpaid)'
  }
  if (dbStatus === 'Released') return 'Completed / Picked Up'
  return dbStatus
}

const fetchMyData = async () => {
  try {
    const myId = localStorage.getItem('userId')
    if (!myId) return router.push('/')

    const historyResponse = await axios.get(`http://localhost:5000/api/requests/history/${myId}`)
    history.value = historyResponse.data
  } catch (error) {
    console.error("Dashboard sync error:", error)
  }
}

onMounted(() => {
  fetchMyData()
  interval = setInterval(fetchMyData, 5000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})

const activeRequests = computed(() => {
  return history.value.filter(req => 
    !['Released', 'Cancelled', 'Rejected'].includes(req.status)
  )
})

const myStats = computed(() => ({
  total: history.value.length,
  completed: history.value.filter(r => r.status === 'Released').length,
  pending: history.value.filter(r => ['Pending', 'Waiting for Printing', 'Ready for Pickup', 'Ready to Print'].includes(r.status)).length
}))

const promptCancel = (requestId) => {
  requestToCancel.value = requestId
  isConfirmModalOpen.value = true
}

const confirmCancel = async () => {
  if (!requestToCancel.value) return
  
  try {
    await axios.put(`http://localhost:5000/api/requests/cancel/${requestToCancel.value}`)
    toast.success("Application Cancelled Successfully.")
    isConfirmModalOpen.value = false
    fetchMyData()
  } catch (error) {
    const errorMsg = error.response?.data?.error || "Error cancelling request."
    toast.error(errorMsg)
    isConfirmModalOpen.value = false
  }
}

const todayString = computed(() => {
  return new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
})
</script>

<template>
  <div class="flex flex-col md:flex-row min-h-screen font-sans pb-[65px] md:pb-0 bg-brand-gray">
    
    <ResidentSidebar activeMenu="Dashboard" />

    <div class="flex-1 p-5 md:p-10 w-full overflow-x-hidden overflow-y-auto">
      
      <!-- Top Header -->
      <div class="flex justify-between items-center mb-8">
        <div>
          <h1 class="m-0 text-gray-900 text-3xl font-bold tracking-tight">Resident Portal</h1>
          <p class="m-0 text-gray-500 mt-1">Welcome back. Track and manage your document requests below.</p>
        </div>
        <div class="hidden md:flex">
          <div class="bg-white border border-gray-200 px-5 py-2.5 rounded-xl text-gray-600 text-sm font-medium shadow-sm">
            {{ todayString }}
          </div>
        </div>
      </div>
      
      <!-- Top Cards: Active Queues -->
      <div class="mb-10">
        <h3 class="m-0 mb-4 text-gray-900 text-xl font-bold tracking-tight">Active Applications</h3>
        
        <div v-if="activeRequests.length > 0" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          <div 
            v-for="queue in activeRequests" 
            :key="queue.request_id"
            class="bg-white p-6 rounded-2xl shadow-sm border flex flex-col transition-all hover:shadow-md"
            :class="[
              queue.status === 'Ready for Pickup' ? 'border-green-300' : 'border-gray-200'
            ]"
          >
            <div class="flex justify-between items-start mb-4">
              <div>
                <h4 class="text-gray-500 m-0 mb-1 uppercase text-[10px] font-bold tracking-widest">{{ queue.doc_name === 'undefined' ? 'Document' : queue.doc_name }}</h4>
                <p class="text-3xl font-black text-brand-blue m-0 leading-none">{{ queue.daily_sequence_no || '--' }}</p>
              </div>
              <span 
                class="px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider"
                :class="[
                  queue.status === 'Ready for Pickup' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'
                ]"
              >
                {{ getDisplayStatus(queue.status, queue.or_number) }}
              </span>
            </div>

            <p class="text-gray-500 text-xs m-0 mb-4 font-medium flex items-center gap-1">
              📅 Scheduled: <span class="text-gray-900 font-bold">{{ queue.pick_up_date ? new Date(queue.pick_up_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : (queue.scheduled_date ? new Date(queue.scheduled_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'TBD') }}</span>
            </p>

            <div v-if="queue.status === 'Ready for Pickup' && !queue.or_number" class="mt-auto p-3 bg-amber-50 rounded-xl border border-amber-200">
              <p class="m-0 text-xs font-bold text-amber-800 mb-1 flex items-center gap-1">💳 Payment Required</p>
              <p class="m-0 text-[11px] text-amber-700 leading-tight">Pay <b>₱{{ queue.base_fee || 0 }}</b> at the cashier.</p>
            </div>

            <div v-if="queue.status === 'Ready for Pickup' && queue.or_number" class="mt-auto p-3 bg-green-500 rounded-xl text-center shadow-sm">
              <p class="m-0 text-[10px] text-green-100 uppercase font-bold tracking-widest mb-1">Official Receipt</p>
              <p class="m-0 text-lg font-black text-white tracking-widest">{{ queue.or_number }}</p>
            </div>
            
            <div v-if="(!queue.status || queue.status === 'undefined' || queue.status === 'Pending')" class="mt-auto pt-4 border-t border-gray-100">
              <p class="m-0 text-[11px] text-gray-400">Waiting for staff review.</p>
            </div>
          </div>
          
          <!-- New Application Button Card -->
          <!-- Stats Summary Card -->
          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-200 flex flex-col justify-between">
            <h4 class="text-gray-500 m-0 mb-4 uppercase text-[10px] font-bold tracking-widest">My Request Summary</h4>
            <div class="flex flex-col gap-3">
              <div class="flex items-center justify-between">
                <span class="text-sm text-gray-500 font-medium flex items-center gap-2">
                  <span class="w-2 h-2 rounded-full bg-gray-300 inline-block"></span>Total Submitted
                </span>
                <span class="text-lg font-black text-gray-800">{{ myStats.total }}</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-sm text-gray-500 font-medium flex items-center gap-2">
                  <span class="w-2 h-2 rounded-full bg-brand-blue inline-block"></span>In Progress
                </span>
                <span class="text-lg font-black text-brand-blue">{{ myStats.pending }}</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-sm text-gray-500 font-medium flex items-center gap-2">
                  <span class="w-2 h-2 rounded-full bg-emerald-400 inline-block"></span>Completed
                </span>
                <span class="text-lg font-black text-emerald-600">{{ myStats.completed }}</span>
              </div>
            </div>
            <div class="mt-4 pt-4 border-t border-gray-100">
              <div class="w-full bg-gray-100 rounded-full h-1.5">
                <div
                  class="bg-brand-blue h-1.5 rounded-full transition-all duration-700"
                  :style="{ width: myStats.total > 0 ? (myStats.completed / myStats.total * 100) + '%' : '0%' }"
                ></div>
              </div>
              <p class="text-[10px] text-gray-400 mt-1.5 font-medium">
                {{ myStats.total > 0 ? Math.round(myStats.completed / myStats.total * 100) : 0 }}% completed
              </p>
            </div>
          </div>

          <!-- New Application Button Card -->
          <div @click="router.push('/document-request')" class="bg-brand-blue hover:bg-brand-light-blue p-6 rounded-2xl shadow-sm border border-blue-600 flex flex-col justify-center items-center text-center cursor-pointer transition-all group min-h-[160px]">
            <div class="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center mb-3 text-white text-2xl group-hover:scale-110 transition-transform">
              ➕
            </div>
            <h4 class="text-white m-0 text-base font-bold">New Application</h4>
          </div>
        </div>

        <!-- Empty State for Active -->
        <div v-else class="bg-white p-8 rounded-2xl shadow-sm border border-gray-200 text-center flex flex-col items-center justify-center h-[200px]">
          <span class="text-4xl mb-3 grayscale opacity-50">📂</span>
          <h4 class="m-0 text-gray-500 text-sm font-bold">No Active Applications</h4>
          <button @click="router.push('/document-request')" class="mt-4 px-5 py-2.5 bg-brand-blue text-white rounded-lg font-bold text-sm border-none cursor-pointer hover:bg-brand-light-blue transition-colors shadow-sm">
            Apply for a Document
          </button>
        </div>
      </div>

      <!-- Transaction History Table -->
      <div class="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
        <div class="p-5 md:p-6 border-b border-gray-100">
          <h3 class="m-0 text-gray-900 text-xl font-bold tracking-tight">Request History</h3>
        </div>
        
        <div class="overflow-x-auto">
          <table class="w-full min-w-[800px] border-collapse text-left">
            <thead class="bg-gray-50">
              <tr>
                <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wider font-bold border-b-2 border-gray-200">Date</th>
                <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wider font-bold border-b-2 border-gray-200">Document</th>
                <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wider font-bold border-b-2 border-gray-200">Payment</th>
                <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wider font-bold border-b-2 border-gray-200">Status</th>
                <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wider font-bold border-b-2 border-gray-200">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="req in history" :key="req.request_id" class="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                <td class="py-4 px-6 text-gray-500 text-sm">
                  {{ new Date(req.date_requested).toLocaleDateString() }}
                  <div v-if="req.pick_up_date" class="text-[10px] text-gray-400 mt-1 uppercase tracking-wider font-bold">
                    For: {{ new Date(req.pick_up_date).toLocaleDateString() }}
                  </div>
                </td>
                <td class="py-4 px-6">
                  <div class="font-bold text-gray-900 text-sm">{{ req.doc_name === 'undefined' ? 'Official Document' : req.doc_name }}</div>
                  <div class="text-[11px] text-gray-500 font-medium mt-1 uppercase tracking-wider">Queue: {{ req.daily_sequence_no || '--' }}</div>
                </td>
                <td class="py-4 px-6">
                  <span v-if="req.or_number" class="px-2.5 py-1 rounded-md text-[10px] font-bold bg-green-50 text-green-700 border border-green-200 tracking-widest">
                    {{ req.or_number }}
                  </span>
                  <div v-else class="text-gray-900 text-sm font-bold">₱{{ req.base_fee || 0 }}</div>
                </td>
                <td class="py-4 px-6">
                  <span 
                    class="px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider border"
                    :class="[
                      (!req.status || req.status === 'undefined' || req.status === 'Pending' || req.status === 'Waiting for Printing') ? 'bg-amber-50 text-amber-700 border-amber-200' : '',
                      req.status === 'Ready for Pickup' ? 'bg-green-50 text-green-700 border-green-200' : '',
                      req.status === 'Released' ? 'bg-brand-blue/10 text-brand-blue border-brand-blue/20' : '',
                      (req.status === 'Cancelled' || req.status === 'Rejected') ? 'bg-red-50 text-red-700 border-red-200' : ''
                    ]"
                  >
                    {{ getDisplayStatus(req.status, req.or_number) }}
                  </span>
                  
                  <div v-if="req.status === 'Rejected' && req.remarks" class="text-red-500 text-xs mt-2 font-medium bg-red-50 p-2 rounded-md border border-red-100">
                    <span class="font-bold uppercase text-[9px] tracking-wider block mb-1">Reason for Rejection:</span>
                    {{ req.remarks }}
                  </div>
                </td>
                <td class="py-4 px-6">
                  <button 
                    v-if="!req.status || req.status === 'undefined' || req.status === 'Pending'"
                    @click="promptCancel(req.request_id)" 
                    class="px-3 py-1.5 text-xs rounded-lg border border-red-300 bg-white text-red-500 hover:bg-red-50 hover:border-red-400 font-bold transition-colors shadow-sm cursor-pointer"
                  >
                    Cancel
                  </button>
                  <span v-else class="text-gray-300 text-sm font-bold">--</span>
                </td>
              </tr>
              <tr v-if="history.length === 0">
                <td colspan="5" class="p-12 text-center text-gray-400 text-sm font-medium">You have no historical requests.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

    </div>
    
    <ResidentBottomNav />

    <!-- Cancellation Modal -->
    <ConfirmModal 
      :isOpen="isConfirmModalOpen"
      title="Cancel Request"
      message="Are you sure you want to cancel this document request? This action cannot be undone."
      confirmText="Yes, Cancel it"
      @confirm="confirmCancel"
      @cancel="isConfirmModalOpen = false"
    />
  </div>
</template>

// client/src/pages/ResidentDashboard.jsx
import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';
import ResidentBottomNav from '../components/ResidentBottomNav';

export default function ResidentDashboard() {
  const navigate = useNavigate();
  
  const [queueInfo, setQueueInfo] = useState({ queueNumber: '--', status: 'Pending', scheduledDate: null, or_number: null, base_fee: 0, doc_name: '' });
  const [history, setHistory] = useState([]);

  // --- UPGRADED: Translation with Fail-Safes ---
  const getDisplayStatus = (dbStatus, orNumber) => {
    // If the database sends "undefined" or nothing, default to Pending
    if (!dbStatus || dbStatus === 'undefined') return 'Pending'; 
    if (dbStatus === 'Waiting for Printing') return 'Waiting for Printing';
    if (dbStatus === 'Ready for Pickup') {
      return orNumber ? 'Ready for Pickup (Paid)' : 'Ready for Pickup (Unpaid)';
    }
    if (dbStatus === 'Released') return 'Completed / Picked Up';
    return dbStatus;
  };

  const fetchMyData = useCallback(async () => {
    try {
      const myId = localStorage.getItem('userId');
      if (!myId) return navigate('/');

      const queueResponse = await axios.get(`http://localhost:5000/api/requests/latest/${myId}`);
      if (queueResponse.data && queueResponse.data.daily_sequence_no) {
        setQueueInfo({
          queueNumber: queueResponse.data.daily_sequence_no,
          status: queueResponse.data.request_status || 'Pending',
          scheduledDate: queueResponse.data.scheduled_date,
          requestId: queueResponse.data.request_id,
          or_number: queueResponse.data.or_number,
          base_fee: queueResponse.data.base_fee,
          doc_name: queueResponse.data.doc_name
        });
      }

      const historyResponse = await axios.get(`http://localhost:5000/api/requests/history/${myId}`);
      setHistory(historyResponse.data);

    } catch (error) {
      console.error("Dashboard sync error:", error);
    }
  }, [navigate]);

  useEffect(() => {
    fetchMyData();
    const interval = setInterval(fetchMyData, 5000); 
    return () => clearInterval(interval);
  }, [fetchMyData]);

  const handleCancel = async (requestId) => {
    if (!window.confirm("Are you sure you want to cancel this request?")) return;

    try {
      await axios.put(`http://localhost:5000/api/requests/cancel/${requestId}`);
      toast.success("Application Cancelled Successfully.");
      fetchMyData(); // Refresh the table
    } catch (error) {
      const errorMsg = error.response?.data?.error || "Error cancelling request.";
      toast.error(errorMsg);
    }
  };
  const handleLogout = () => {
    localStorage.clear();
    navigate('/');
  };

  return (
    <div className="flex flex-col md:flex-row min-h-screen font-sans pb-[65px] md:pb-0" style={{ background: 'transparent' }}>
      
      {/* Sidebar (Hidden on Mobile) */}
      <div className="glass-panel hidden md:flex flex-col w-[280px] p-[30px_20px] sticky top-0 h-screen overflow-y-auto z-10" style={{ borderRight: '1px solid rgba(255,255,255,0.05)', background: 'rgba(15, 23, 42, 0.6)' }}>
        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '40px', padding: '0 10px' }}>
          <div style={{ width: '36px', height: '36px', background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '12px', boxShadow: '0 0 15px rgba(59,130,246,0.2)' }}>
            <span style={{ color: 'var(--neon-blue)', fontSize: '18px' }}>🏘️</span>
          </div>
          <div>
             <h2 style={{ fontSize: '18px', margin: 0, fontWeight: 'bold', color: 'white', letterSpacing: '0.5px' }}>Resident Portal</h2>
             <p style={{ margin: 0, fontSize: '12px', color: 'var(--neon-blue)', textTransform: 'uppercase', letterSpacing: '1px' }}>E-Services</p>
          </div>
        </div>
        
        <div style={{ flex: 1 }}>
          <NavItem to="/resident-dashboard" icon="📊" label="Dashboard" />
          <NavItem to="/document-request" icon="📄" label="Request Document" />
          <NavItem to="/request-history" icon="🕒" label="Request History" badgeCount={history.length} />
          <NavItem to="/profile" icon="👤" label="Profile Settings" />
        </div>
        <button onClick={handleLogout} className="transition-all duration-300 flex items-center px-4 py-3 rounded-xl cursor-pointer text-slate-400 hover:bg-[rgba(244,63,94,0.15)] hover:text-[#f43f5e] hover:border hover:border-[rgba(244,63,94,0.3)] w-full mt-4" style={{ border: '1px solid transparent', outline: 'none', background: 'transparent' }}>
          <span style={{ marginRight: '12px', fontSize: '18px' }}>🚪</span>
          <span style={{ fontWeight: 'bold' }}>Logout</span>
        </button>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 p-5 md:p-[40px] w-full overflow-x-hidden">
        
        {/* Top Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
          <div>
             <h1 style={{ margin: '0 0 5px 0', color: 'var(--text-main)', fontSize: '28px', fontWeight: 'bold' }}>Resident Portal</h1>
             <p style={{ margin: 0, color: 'var(--text-muted)' }}>Welcome back. Track and manage your document requests below.</p>
          </div>
          <div className="hidden md:flex gap-[15px]">
            <div className="glass-panel" style={{ padding: '10px 20px', borderRadius: '12px', color: 'var(--text-muted)', fontSize: '14px' }}>
               {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
          </div>
        </div>
        
        {/* Top Cards (Bento Grid) */}
        <div className="flex flex-col md:flex-row gap-[20px] mt-[20px] mb-[40px]">
          
          <div className="glass-card" style={{ flex: 1, padding: '25px', display: 'flex', flexDirection: 'column', justifyItems: 'center', justifyContent: 'center' }}>
            <h4 style={{ color: 'var(--text-muted)', margin: '0 0 5px 0', textTransform: 'uppercase', fontSize: '14px', fontWeight: '600' }}>Your Latest Queue</h4>
            <p style={{ fontSize: '38px', fontWeight: 'bold', color: 'var(--text-main)', margin: 0 }}>{queueInfo.queueNumber}</p>
            {queueInfo.scheduledDate && (
              <p style={{ color: 'var(--text-muted)', fontSize: '13px', margin: '5px 0 0 0', fontWeight: '500' }}>
                For: {new Date(queueInfo.scheduledDate).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })}
              </p>
            )}
          </div>
          
          <div className="glass-card" style={{ flex: 1.2, padding: '25px', display: 'flex', flexDirection: 'column', justifyItems: 'center', justifyContent: 'center' }}>
            <h4 style={{ color: 'var(--text-muted)', margin: '0 0 5px 0', textTransform: 'uppercase', fontSize: '14px', fontWeight: '600' }}>Latest Status</h4>
            <h2 style={{ fontSize: '22px', fontWeight: 'bold', margin: '0', 
              color: queueInfo.status === 'Ready for Pickup' ? 'var(--neon-green)' : queueInfo.status === 'Released' ? 'var(--neon-blue)' : queueInfo.status === 'Cancelled' ? '#f43f5e' : queueInfo.status === 'Waiting for Printing' ? '#fbbf24' : '#fbbf24' }}>
              {getDisplayStatus(queueInfo.status, queueInfo.or_number)}
            </h2>

            {/* If Ready for Pickup & NOT paid yet */}
            {queueInfo.status === 'Ready for Pickup' && !queueInfo.or_number && (
              <div style={{ marginTop: '15px', padding: '12px', background: 'rgba(251, 191, 36, 0.1)', borderRadius: '8px', border: '1px solid rgba(251,191,36,0.3)' }}>
                <p style={{ margin: '0 0 4px 0', fontSize: '12px', fontWeight: 'bold', color: '#fbbf24' }}>💳 Payment Required</p>
                <p style={{ margin: 0, fontSize: '12px', color: '#fef3c7' }}>
                  Please proceed to the Barangay Hall Cashier with your Queue Number (<b>{queueInfo.queueNumber}</b>) to pay the fee (<b>₱{queueInfo.base_fee || 0}</b>).
                </p>
              </div>
            )}

            {/* If Ready for Pickup & ALREADY paid */}
            {queueInfo.status === 'Ready for Pickup' && queueInfo.or_number && (
              <div style={{ marginTop: '15px', padding: '12px', background: 'rgba(16, 185, 129, 0.1)', borderRadius: '8px', border: '1px solid rgba(16,185,129,0.3)', textAlign: 'center' }}>
                <p style={{ margin: '0 0 4px 0', fontSize: '11px', color: 'var(--neon-green)', textTransform: 'uppercase', fontWeight: 'bold' }}>Official Receipt Issued</p>
                <p style={{ margin: 0, fontSize: '22px', fontWeight: 'bold', color: 'white', letterSpacing: '1px' }}>{queueInfo.or_number}</p>
                <p style={{ margin: '5px 0 0 0', fontSize: '11px', color: '#a7f3d0' }}>Present this OR code to the releasing officer.</p>
              </div>
            )}
          </div>
          
          <div onClick={() => navigate('/document-request')} className="glass-card transition-all duration-300 hover:scale-105 cursor-pointer" style={{ flex: 1, padding: '25px', display: 'flex', flexDirection: 'column', justifyItems: 'center', justifyContent: 'center', background: 'rgba(59, 130, 246, 0.2)', border: '1px solid rgba(59,130,246,0.3)' }}>
            <div style={{ width: '40px', height: '40px', background: 'rgba(255,255,255,0.1)', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '15px', color: 'var(--text-main)' }}>➕</div>
            <h4 style={{ color: 'var(--text-main)', margin: '0 0 5px 0', fontSize: '18px', fontWeight: 'bold' }}>New Application</h4>
            <p style={{ color: 'var(--neon-cyan)', margin: 0, fontSize: '13px' }}>Click here to apply for a new Document ➔</p>
          </div>
        </div>

        {/* Transaction History Table */}
        <div className="glass-card" style={{ overflow: 'hidden' }}>
          <div style={{ padding: '20px 25px', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
            <h3 style={{ margin: 0, color: 'var(--text-main)', fontSize: '18px', fontWeight: '600' }}>My Request History</h3>
          </div>
          
          <div className="overflow-x-auto">
            <table style={{ width: '100%', minWidth: '700px', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.05)', color: 'var(--text-muted)', textAlign: 'left', fontSize: '13px', textTransform: 'uppercase' }}>
                <th style={{ padding: '15px 25px', fontWeight: '600' }}>Requested</th>
                <th style={{ padding: '15px 25px', fontWeight: '600' }}>Pick-up Date</th>
                <th style={{ padding: '15px 25px', fontWeight: '600' }}>Document Type</th>
                <th style={{ padding: '15px 25px', fontWeight: '600' }}>Payment / OR #</th>
                <th style={{ padding: '15px 25px', fontWeight: '600' }}>Status</th>
                <th style={{ padding: '15px 25px', fontWeight: '600' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {history.length > 0 ? (
                history.map((req) => {
                  const safeDocName = req.doc_name === 'undefined' ? 'Official Document' : req.doc_name;
                  const rawStatus = (!req.status || req.status === 'undefined') ? 'Pending' : req.status;

                  return (
                    <tr key={req.request_id} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }} className="hover:bg-[rgba(255,255,255,0.02)] transition-colors duration-150">
                      <td style={{ padding: '15px 25px', color: 'var(--text-muted)', fontSize: '14px' }}>{new Date(req.date_requested).toLocaleDateString()}</td>
                      <td style={{ padding: '15px 25px', color: 'var(--text-main)', fontSize: '14px', fontWeight: '600' }}>{req.pick_up_date ? new Date(req.pick_up_date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }) : 'N/A'}</td>
                      <td style={{ padding: '15px 25px', fontWeight: '500', color: 'var(--text-main)' }}>
                        {safeDocName}
                        <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Fee: ₱{req.base_fee || 0}</div>
                      </td>
                      <td style={{ padding: '15px 25px' }}>
                        {req.or_number ? (
                          <span style={{ padding: '4px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 'bold', background: 'rgba(16,185,129,0.1)', color: 'var(--neon-green)', border: '1px solid rgba(16,185,129,0.2)' }}>
                            OR: {req.or_number}
                          </span>
                        ) : (
                          <span style={{ color: 'var(--text-muted)', fontSize: '12px' }}>--</span>
                        )}
                      </td>
                      <td style={{ padding: '15px 25px' }}>
                      <span style={{
                        padding: '4px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 'bold',
                        background: rawStatus === 'Ready for Pickup' ? 'rgba(16,185,129,0.1)' : rawStatus === 'Released' ? 'rgba(59,130,246,0.1)' : rawStatus === 'Cancelled' || rawStatus === 'Rejected' ? 'rgba(244,63,94,0.1)' : 'rgba(251,191,36,0.1)',
                        color: rawStatus === 'Ready for Pickup' ? 'var(--neon-green)' : rawStatus === 'Released' ? 'var(--neon-blue)' : rawStatus === 'Cancelled' || rawStatus === 'Rejected' ? '#f43f5e' : '#fbbf24',
                        border: `1px solid ${rawStatus === 'Ready for Pickup' ? 'rgba(16,185,129,0.2)' : rawStatus === 'Released' ? 'rgba(59,130,246,0.2)' : rawStatus === 'Cancelled' || rawStatus === 'Rejected' ? 'rgba(244,63,94,0.2)' : 'rgba(251,191,36,0.2)'}`
                      }}>
                        {getDisplayStatus(rawStatus, req.or_number)}
                      </span>
                      
                      {/* Display the Staff's reason for rejection */}
                      {rawStatus === 'Rejected' && req.remarks && (
                        <div style={{ color: '#f43f5e', fontSize: '12px', marginTop: '6px', fontWeight: '500' }}>
                          Reason: {req.remarks}
                        </div>
                      )}
                    </td>
                      <td style={{ padding: '15px 25px' }}>
                        {rawStatus === 'Pending' ? (
                          <button onClick={() => handleCancel(req.request_id)} className="transition-colors hover:bg-[rgba(244,63,94,0.1)] hover:border-[#f43f5e]" style={{ padding: '6px 12px', fontSize: '12px', borderRadius: '6px', border: '1px solid rgba(244,63,94,0.5)', background: 'transparent', color: '#f43f5e', cursor: 'pointer', fontWeight: '600' }}>
                            Cancel
                          </button>
                        ) : (
                          <span style={{ color: 'var(--text-muted)', fontSize: '12px' }}>--</span>
                        )}
                      </td>
                    </tr>
                  )
                })
              ) : (
                <tr><td colSpan="6" style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>You have no past requests.</td></tr>
              )}
            </tbody>
          </table>
          </div>
        </div>

      </div>
      
      {/* Mobile Bottom Navigation */}
      <ResidentBottomNav />
    </div>
  );
}
