// client-vue/src/views/StaffHome.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
import StaffSidebar from '../components/StaffSidebar.vue'

const router = useRouter()
const stats = ref({
  totalPending: 0,
  totalReady: 0,
  totalPickup: 0
})
const counts = ref({ pending: 0, ready: 0, pickup: 0 })
const recentTasks = ref([])
const currentTime = ref('')
const currentDate = ref('')
const canReview = ref(false)
const isStatsLoading = ref(true)
let interval = null

const updateDateTime = () => {
  const now = new Date()
  currentTime.value = now.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true })
  currentDate.value = now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })
}

const fetchStaffData = async () => {
  const staffId = localStorage.getItem('userId')
  if (!staffId) return

  try {
    const profileRes = await axios.get(`http://localhost:5000/api/staff/profile/${staffId}`)
    canReview.value = Number(profileRes.data.can_review) === 1
    localStorage.setItem('canReview', profileRes.data.can_review)

    const res = await axios.get('http://localhost:5000/api/staff/pending-requests')
    const pending = res.data.filter(r => r.status === 'Pending')
    const ready = res.data.filter(r => r.status === 'Ready to Print' || r.status === 'Waiting for Printing')
    const pickup = res.data.filter(r => r.status === 'Ready for Pickup')
    
    stats.value.totalPending = pending.length
    stats.value.totalReady = ready.length
    stats.value.totalPickup = pickup.length
    counts.value = { pending: pending.length, ready: ready.length, pickup: pickup.length }
    recentTasks.value = res.data.slice(0, 5)
  } catch (error) {
    console.error("Failed to fetch staff data", error)
  } finally {
    isStatsLoading.value = false
  }
}

onMounted(() => {
  canReview.value = localStorage.getItem('canReview') === '1'
  updateDateTime()
  setInterval(updateDateTime, 1000)
  fetchStaffData()
  interval = setInterval(fetchStaffData, 5000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})
</script>

<template>
  <div class="flex h-screen bg-brand-gray font-sans overflow-hidden">
    
    <StaffSidebar activeMenu="Home Dashboard" :counts="counts" :canReview="canReview" />

    <!-- Main Content -->
    <div class="flex-1 p-8 overflow-y-auto">
      
      <!-- Top Header -->
      <div class="flex justify-between items-center mb-8">
        <h1 class="text-3xl font-bold text-[#1e293b] m-0">Staff Workspace</h1>
        
        <div class="flex gap-4">
          <div class="dashboard-card py-2 px-4 shadow-sm border border-gray-100 flex flex-col justify-center items-end bg-white rounded-lg">
            <span class="text-xs text-gray-500 font-medium">{{ currentDate }}</span>
            <span class="text-base font-bold text-gray-800">{{ currentTime }}</span>
          </div>
        </div>
      </div>

      <!-- Quick Metrics -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        <!-- Tasks to Review: shows access card if no privilege -->
        <div v-if="canReview" class="dashboard-card border-l-4 border-l-amber-500 flex items-center gap-4 cursor-pointer hover:bg-gray-50" @click="router.push('/staff-pending')">
            <div class="w-12 h-12 rounded-full bg-amber-50 flex items-center justify-center text-amber-500">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            </div>
            <div>
              <h4 class="text-sm font-semibold text-gray-500 m-0 uppercase tracking-wide">Tasks to Review</h4>
              <p class="text-3xl font-bold text-gray-800 m-0 mt-1">{{ stats.totalPending }}</p>
            </div>
        </div>
        <div v-else class="dashboard-card border-l-4 border-l-gray-300 flex items-center gap-4 opacity-60 cursor-not-allowed select-none">
            <div class="w-12 h-12 rounded-full bg-gray-100 flex items-center justify-center text-gray-400">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
            </div>
            <div>
              <h4 class="text-sm font-semibold text-gray-400 m-0 uppercase tracking-wide">Tasks to Review</h4>
              <p class="text-xs text-gray-400 mt-1 font-medium">No Access — Contact Admin</p>
            </div>
        </div>

        <div class="dashboard-card border-l-4 border-l-emerald-500 flex items-center gap-4 cursor-pointer hover:bg-gray-50" @click="router.push('/staff-ready-to-print')">
            <div class="w-12 h-12 rounded-full bg-emerald-50 flex items-center justify-center text-emerald-500">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
            </div>
            <div>
              <h4 class="text-sm font-semibold text-gray-500 m-0 uppercase tracking-wide">Printing & Releases</h4>
              <p class="text-3xl font-bold text-gray-800 m-0 mt-1">{{ stats.totalReady + stats.totalPickup }}</p>
            </div>
        </div>
      </div>

      <!-- Recent Tasks -->
      <div class="dashboard-card">
        <div class="flex items-center gap-2 mb-6 border-b border-gray-100 pb-4">
          <svg class="w-5 h-5 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"></path></svg>
          <h3 class="text-lg font-bold text-gray-700 m-0">Recent Resident Requests</h3>
        </div>
        <div class="overflow-x-auto">
          <table class="w-full text-left text-sm text-gray-600">
            <thead class="text-xs text-gray-500 uppercase bg-gray-50">
              <tr>
                <th class="px-6 py-3 rounded-tl-lg">Resident Name</th>
                <th class="px-6 py-3">Document Type</th>
                <th class="px-6 py-3">Status</th>
                <th class="px-6 py-3 rounded-tr-lg">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(req, index) in recentTasks" :key="index" class="bg-white border-b hover:bg-gray-50">
                <td class="px-6 py-4 font-medium text-gray-900">{{ req.first_name }} {{ req.last_name }}</td>
                <td class="px-6 py-4 font-medium text-gray-700">{{ req.doc_name }}</td>
                <td class="px-6 py-4">
                  <span :class="[
                    'px-2.5 py-0.5 rounded-full text-xs font-semibold',
                    req.status === 'Pending' ? 'bg-amber-100 text-amber-800' :
                    req.status === 'Ready for Pickup' ? 'bg-blue-100 text-blue-800' :
                    req.status === 'Waiting for Printing' || req.status === 'Ready to Print' ? 'bg-purple-100 text-purple-800' :
                    'bg-emerald-100 text-emerald-800'
                  ]">
                    {{ req.status }}
                  </span>
                </td>
                <td class="px-6 py-4">
                  <button 
                    v-if="req.status === 'Pending' && canReview"
                    @click="router.push('/staff-pending')"
                    class="text-amber-600 hover:underline font-semibold text-xs"
                  >Review</button>
                  <button 
                    v-else-if="req.status === 'Waiting for Printing' || req.status === 'Ready to Print'"
                    @click="router.push('/staff-ready-to-print')"
                    class="text-emerald-600 hover:underline font-semibold text-xs"
                  >Print</button>
                  <button 
                    v-else-if="req.status === 'Ready for Pickup'"
                    @click="router.push('/staff-ready-to-print')"
                    class="text-blue-600 hover:underline font-semibold text-xs"
                  >Release</button>
                  <span v-else class="text-gray-300 text-xs">—</span>
                </td>
              </tr>
              <tr v-if="isStatsLoading">
                <td colspan="4" class="px-6 py-8 text-center text-gray-400">Loading recent tasks...</td>
              </tr>
              <tr v-else-if="recentTasks.length === 0">
                <td colspan="4" class="px-6 py-8 text-center text-gray-400">No active tasks.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

// client/src/pages/StaffHome.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

export default function StaffHome() {
  const navigate = useNavigate();
  const staffId = localStorage.getItem('userId');
  
  const [stats, setStats] = useState({ pending: 0, ready: 0, released: 0 });
  const [canReview, setCanReview] = useState(localStorage.getItem('canReview') === '1');
  
  // FIX: Added the counts state to track the notifications on the Home page
  const [counts, setCounts] = useState({ pending: 0, ready: 0 });

  useEffect(() => {
    const fetchDataAndSync = async () => {
      try {
        // 1. Sync Permissions silently
        const profileRes = await axios.get(`http://localhost:5000/api/staff/profile/${staffId}`);
        const currentPermission = profileRes.data.can_review === 1;
        setCanReview(currentPermission);
        localStorage.setItem('canReview', profileRes.data.can_review);

        // 2. Fetch Dashboard Totals (for the big cards)
        const statsRes = await axios.get('http://localhost:5000/api/staff/dashboard-stats');
        setStats(statsRes.data);

        // 3. Fetch specific queue counts (for the red notification dots)
        const requestsRes = await axios.get('http://localhost:5000/api/staff/pending-requests');
        setCounts({
          pending: requestsRes.data.filter(req => req.status === 'Pending').length,
          ready: requestsRes.data.filter(req => req.status === 'Ready to Print').length
        });
      } catch (error) {
        console.error("Sync failed", error);
      }
    };

    fetchDataAndSync();
    const interval = setInterval(fetchDataAndSync, 5000);
    return () => clearInterval(interval);
  }, [staffId]);

  const handleLogout = () => {
    localStorage.clear();
    navigate('/');
  };

  const NavItem = ({ to, icon, label, badgeCount }) => {
    const isActive = location.pathname === to;
    return (
      <p 
        onClick={() => navigate(to)} 
        className={`transition-all duration-300 flex items-center px-4 py-3 rounded-xl cursor-pointer ${isActive ? 'bg-[rgba(16,185,129,0.15)] text-[var(--neon-green)] font-bold shadow-[inset_0_0_12px_rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.2)]' : 'text-slate-400 hover:bg-[rgba(255,255,255,0.05)] hover:text-white'}`}
        style={{ margin: '8px 0' }}
      >
        <span style={{ marginRight: '12px', fontSize: '18px', filter: isActive ? 'drop-shadow(0 0 4px rgba(16,185,129,0.5))' : 'none' }}>{icon}</span>
        {label}
        {badgeCount > 0 && <span style={{
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
            background: 'rgba(244,63,94,0.2)', color: '#f43f5e', border: '1px solid rgba(244,63,94,0.4)', borderRadius: '50%',
            minWidth: '22px', height: '22px', fontSize: '12px', fontWeight: 'bold',
            marginLeft: 'auto'
        }}>{badgeCount}</span>}
      </p>
    );
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: 'transparent', overflowY: 'hidden' }}>
      
      {/* Sidebar for Staff */}
      <div className="glass-panel hidden md:flex" style={{ width: '280px', borderRight: '1px solid rgba(255,255,255,0.05)', padding: '30px 20px', flexDirection: 'column', zIndex: 10, background: 'rgba(15, 23, 42, 0.6)' }}>
        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '40px', padding: '0 10px' }}>
          <div style={{ width: '36px', height: '36px', background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '12px', boxShadow: '0 0 15px rgba(16,185,129,0.2)' }}>
            <span style={{ color: 'var(--neon-green)', fontSize: '18px' }}>👨‍💼</span>
          </div>
          <div>
             <h2 style={{ fontSize: '18px', margin: 0, fontWeight: 'bold', color: 'white', letterSpacing: '0.5px' }}>Staff Portal</h2>
             <p style={{ margin: 0, fontSize: '12px', color: 'var(--neon-green)', textTransform: 'uppercase', letterSpacing: '1px' }}>Operations</p>
          </div>
        </div>
        
        <div style={{ flex: 1 }}>
          <NavItem to="/staff-home" icon="📊" label="Dashboard Overview" />
          {canReview && (
            <NavItem to="/staff-pending" icon="📋" label="Review Applications" badgeCount={counts.pending} />
          )}
          <NavItem to="/staff-ready" icon="🔖" label="Ready to Release" badgeCount={counts.ready} />
          <NavItem to="/document-records" icon="📄" label="Document Records" />
        </div>

        <button onClick={handleLogout} className="transition-all duration-300 flex items-center px-4 py-3 rounded-xl cursor-pointer text-slate-400 hover:bg-[rgba(244,63,94,0.15)] hover:text-[#f43f5e] hover:border hover:border-[rgba(244,63,94,0.3)] w-full mt-4" style={{ border: '1px solid transparent', outline: 'none', background: 'transparent' }}>
          <span style={{ marginRight: '12px', fontSize: '18px' }}>🚪</span>
          <span style={{ fontWeight: 'bold' }}>Logout</span>
        </button>
      </div>

      <div style={{ flex: 1, padding: '40px', overflowY: 'auto' }}>
        
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
          <h1 style={{ margin: 0, color: 'var(--text-main)', fontSize: '28px', fontWeight: 'bold' }}>Dashboard Overview</h1>
          <div style={{ display: 'flex', gap: '15px' }}>
            <div className="glass-panel" style={{ padding: '10px 20px', borderRadius: '12px', color: 'var(--text-muted)', fontSize: '14px' }}>
               {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
          </div>
        </div>
        
        <div style={{ display: 'flex', gap: '20px', marginBottom: '30px', flexWrap: 'wrap' }}>
          
          <div className="glass-card" style={{ flex: 1, minWidth: '200px', padding: '25px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }} onClick={() => navigate('/staff-pending')}>
            <div>
              <p style={{ margin: '0 0 5px 0', color: 'var(--text-muted)', fontSize: '14px', fontWeight: '600', textTransform: 'uppercase' }}>Active Pending</p>
              <h3 style={{ margin: 0, color: 'var(--text-main)', fontSize: '32px', fontWeight: 'bold' }}>{stats.pending}</h3>
            </div>
            <div style={{ width: '48px', height: '48px', borderRadius: '12px', background: 'rgba(59, 130, 246, 0.1)', color: 'var(--neon-blue)', border: '1px solid rgba(59,130,246,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '24px' }}>
              📋
            </div>
          </div>
          
          <div className="glass-card" style={{ flex: 1, minWidth: '200px', padding: '25px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }} onClick={() => navigate('/staff-ready')}>
            <div>
              <p style={{ margin: '0 0 5px 0', color: 'var(--text-muted)', fontSize: '14px', fontWeight: '600', textTransform: 'uppercase' }}>Ready for Pickup</p>
              <h3 style={{ margin: 0, color: 'var(--text-main)', fontSize: '32px', fontWeight: 'bold' }}>{stats.ready}</h3>
            </div>
            <div style={{ width: '48px', height: '48px', borderRadius: '12px', background: 'rgba(16, 185, 129, 0.1)', color: 'var(--neon-green)', border: '1px solid rgba(16,185,129,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '24px' }}>
              🔖
            </div>
          </div>

          <div className="glass-card" style={{ flex: 1, minWidth: '200px', padding: '25px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }} onClick={() => navigate('/document-records')}>
            <div>
              <p style={{ margin: '0 0 5px 0', color: 'var(--text-muted)', fontSize: '14px', fontWeight: '600', textTransform: 'uppercase' }}>Completed Today</p>
              <h3 style={{ margin: 0, color: 'var(--text-main)', fontSize: '32px', fontWeight: 'bold' }}>{stats.released}</h3>
            </div>
            <div style={{ width: '48px', height: '48px', borderRadius: '12px', background: 'rgba(6, 182, 212, 0.1)', color: 'var(--neon-cyan)', border: '1px solid rgba(6,182,212,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '24px' }}>
              ✅
            </div>
          </div>
        </div>

        {/* System Notice Section */}
        <div className="glass-card" style={{ padding: '25px', display: 'flex', alignItems: 'flex-start', gap: '15px' }}>
          <div style={{ fontSize: '24px', filter: 'drop-shadow(0 0 4px rgba(255,255,255,0.4))' }}>ℹ️</div>
          <div>
            <h4 style={{ margin: '0 0 5px 0', color: 'white', fontSize: '16px', fontWeight: '600' }}>System Information</h4>
            <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '14px' }}>
              Current Role: <span style={{ fontWeight: 'bold', color: 'var(--text-main)' }}>{localStorage.getItem('userRole') || 'Front Desk Staff'}</span> | 
              Review Access: <span style={{ fontWeight: 'bold', color: canReview ? 'var(--neon-green)' : '#ea580c' }}>{canReview ? " ENABLED" : " DISABLED"}</span>
            </p>
            {!canReview && (
              <p style={{ margin: '10px 0 0 0', color: '#f43f5e', fontSize: '13px', fontWeight: '600' }}>
                * You cannot approve new document requests until the Admin grants you permission.
              </p>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
