// client-vue/src/views/SystemSettings.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
import AdminSidebar from '../components/AdminSidebar.vue'
import { useToast } from '../composables/useToast'

const toast = useToast()

const router = useRouter()
const defaultLimit = ref(10)
const isUpdating = ref(false)
const dateLimits = ref([])
const newException = ref({ date: '', limit: 0, reason: '' })
const badgeCounts = ref({ pending: 0, ready: 0, residentApprovals: 0 })

const fetchData = async () => {
  try {
    const [defaultRes, dateRes] = await Promise.all([
      axios.get('http://localhost:5000/api/settings/daily-limit'),
      axios.get('http://localhost:5000/api/settings/date-limits')
    ])
    if (defaultRes.data && defaultRes.data.limit !== undefined) {
      defaultLimit.value = defaultRes.data.limit
    }
    dateLimits.value = dateRes.data || []
  } catch (err) {
    console.error("Error fetching settings", err)
  }
}

const fetchCounts = async () => {
  try {
    const [requestsRes, residentsRes] = await Promise.all([
      axios.get('http://localhost:5000/api/staff/pending-requests'),
      axios.get('http://localhost:5000/api/admin/pending-residents')
    ])
    const pending = requestsRes.data.filter(req => req.status === 'Pending').length
    const ready = requestsRes.data.filter(req => req.status === 'Ready to Print').length
    const residentApprovals = residentsRes.data.length
    badgeCounts.value = { pending, ready, residentApprovals }
  } catch (error) {
    console.error("Failed to fetch notification counts", error)
  }
}

onMounted(() => {
  const role = localStorage.getItem('role')
  if (role !== 'Admin') {
    router.push('/')
    return
  }
  fetchData()
  fetchCounts()
  setInterval(fetchCounts, 5000)
})

const handleUpdateDefault = async () => {
  isUpdating.value = true
  try {
    const adminId = localStorage.getItem('userId')
    await axios.put('http://localhost:5000/api/settings/daily-limit', { limit: defaultLimit.value, adminId })
    toast.success('Default limit updated successfully!')
  } catch (err) {
    toast.error('Failed to update default limit.')
  } finally {
    isUpdating.value = false
  }
}

const handleAddException = async () => {
  try {
    const adminId = localStorage.getItem('userId')
    await axios.post('http://localhost:5000/api/settings/date-limits', { 
      ...newException.value,
      adminId
    })
    toast.success('Date exception added successfully!')
    newException.value = { date: '', limit: 0, reason: '' }
    fetchData()
  } catch (err) {
    toast.error('Failed to add date exception.')
  }
}

const handleDeleteException = async (id) => {
  if (!window.confirm("Are you sure you want to delete this exception?")) return
  try {
    const adminId = localStorage.getItem('userId')
    await axios.delete(`http://localhost:5000/api/settings/date-limits/${id}`, {
      data: { adminId }
    })
    toast.success('Exception removed successfully!')
    fetchData()
  } catch (err) {
    toast.error('Failed to delete exception.')
  }
}
</script>

<template>
  <div class="flex h-screen bg-brand-gray font-sans overflow-hidden">
    
    <AdminSidebar activeMenu="System Settings" :badgeCounts="badgeCounts" />

    <div class="flex-1 p-8 overflow-y-auto">
      <div class="mb-8">
        <h1 class="m-0 text-gray-900 text-3xl font-bold">System Settings</h1>
        <p class="text-gray-500 mt-1">Configure global rules and daily processing limits for the Barangay Fortune system.</p>
      </div>

      <div class="flex flex-col gap-8 max-w-3xl">

        <!-- Default Daily Limit -->
        <div class="bg-white p-8 rounded-xl shadow-sm border border-gray-100">
          <h3 class="m-0 mb-2.5 text-gray-800 flex items-center gap-2 text-xl font-bold">
            ⚙️ Default Daily Limit
          </h3>
          <p class="text-gray-500 text-sm mb-6 leading-relaxed">
            Set the default maximum number of documents the system can process per day.
            This applies to all standard days unless overridden by a date exception below.
          </p>

          <div class="p-3 mb-6 rounded-lg bg-red-50 text-red-700 text-sm font-semibold border border-red-200 flex items-center gap-2.5">
            <span>🚫</span> Sunday operations are automatically closed and hidden from residents.
          </div>

          <form @submit.prevent="handleUpdateDefault" class="flex items-end gap-4">
            <div class="flex-1">
              <label class="block text-xs font-bold text-gray-500 mb-2 uppercase tracking-wide">Documents per Day (Default)</label>
              <input 
                type="number" 
                min="1"
                v-model="defaultLimit" 
                required 
                class="w-full px-4 py-2.5 rounded-lg border border-gray-300 text-lg font-bold text-gray-900 outline-none focus:ring-2 focus:ring-brand-blue"
              />
            </div>
            <button 
              type="submit" 
              :disabled="isUpdating"
              class="px-6 py-3 bg-brand-blue hover:bg-brand-light-blue text-white font-bold rounded-lg transition-colors whitespace-nowrap disabled:bg-gray-400 disabled:cursor-not-allowed"
            >
              {{ isUpdating ? 'Saving...' : 'Save Limit' }}
            </button>
          </form>
        </div>

        <!-- Date-Specific Exceptions -->
        <div class="bg-white p-8 rounded-xl shadow-sm border border-gray-100">
          <h3 class="m-0 mb-2.5 text-gray-800 flex items-center gap-2 text-xl font-bold">
            📅 Specific Date Exceptions
          </h3>
          <p class="text-gray-500 text-sm mb-6 leading-relaxed">
            Override the default limit for specific dates — such as holidays, half-days, or special events.
            Setting a limit to <strong>0</strong> means the system is closed for that date.
          </p>

          <div class="bg-gray-50 border border-gray-200 rounded-lg p-5 mb-6">
            <h4 class="m-0 mb-4 text-gray-700 text-sm font-bold uppercase">Add New Exception</h4>
            <form @submit.prevent="handleAddException" class="grid grid-cols-[1fr_1fr_2fr_auto] gap-3 items-end">
              <div>
                <label class="block text-[11px] font-bold text-gray-500 mb-1">DATE</label>
                <input 
                  type="date" 
                  v-model="newException.date"
                  required
                  class="w-full p-2 rounded-md border border-gray-300 outline-none focus:ring-2 focus:ring-brand-blue text-sm"
                />
              </div>
              <div>
                <label class="block text-[11px] font-bold text-gray-500 mb-1">LIMIT (0 = CLOSED)</label>
                <input 
                  type="number" 
                  min="0"
                  v-model="newException.limit"
                  required
                  class="w-full p-2 rounded-md border border-gray-300 outline-none focus:ring-2 focus:ring-brand-blue text-sm font-bold"
                />
              </div>
              <div>
                <label class="block text-[11px] font-bold text-gray-500 mb-1">REASON</label>
                <input 
                  type="text" 
                  v-model="newException.reason"
                  required
                  placeholder="e.g. Holiday, Half-Day"
                  class="w-full p-2 rounded-md border border-gray-300 outline-none focus:ring-2 focus:ring-brand-blue text-sm"
                />
              </div>
              <button type="submit" class="px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white font-bold rounded-md transition-colors whitespace-nowrap text-sm">
                + Add
              </button>
            </form>
          </div>

          <div class="overflow-x-auto rounded-lg border border-gray-200">
            <table class="w-full text-left border-collapse">
              <thead>
                <tr class="bg-gray-50 border-b-2 border-gray-200">
                  <th class="py-3 px-4 text-gray-500 text-xs font-bold uppercase">Date</th>
                  <th class="py-3 px-4 text-gray-500 text-xs font-bold uppercase">Limit</th>
                  <th class="py-3 px-4 text-gray-500 text-xs font-bold uppercase">Reason</th>
                  <th class="py-3 px-4 text-gray-500 text-xs font-bold uppercase">Action</th>
                </tr>
              </thead>
              <tbody>
                <tr v-if="dateLimits.length === 0">
                  <td colspan="4" class="p-8 text-center text-gray-400 text-sm">No date exceptions configured.</td>
                </tr>
                <tr v-for="item in dateLimits" :key="item.id" class="border-b border-gray-50 hover:bg-gray-50">
                  <td class="py-3.5 px-4 font-bold text-gray-800 text-sm">
                    {{ new Date(item.specific_date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }) }}
                  </td>
                  <td class="py-3.5 px-4 text-sm">
                    <span v-if="item.document_limit === 0" class="bg-red-50 text-red-700 px-2.5 py-1 rounded-md font-bold text-xs border border-red-100">CLOSED (0)</span>
                    <span v-else class="font-bold text-gray-800">{{ item.document_limit }}</span>
                  </td>
                  <td class="py-3.5 px-4 text-gray-600 text-sm">{{ item.reason }}</td>
                  <td class="py-3.5 px-4">
                    <button 
                      @click="handleDeleteException(item.id)"
                      class="px-3 py-1.5 bg-red-50 text-red-600 border border-red-200 rounded-md font-bold text-xs hover:bg-red-100 transition-colors"
                    >
                      Remove
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// client/src/pages/SystemSettings.jsx
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import AdminSidebar from '../components/AdminSidebar';
import toast, { Toaster } from 'react-hot-toast';

export default function SystemSettings() {
  const navigate = useNavigate();

  // Default daily limit state
  const [defaultLimit, setDefaultLimit] = useState(10);
  const [isUpdating, setIsUpdating] = useState(false);

  // Date-specific exceptions state
  const [dateLimits, setDateLimits] = useState([]);
  const [newException, setNewException] = useState({ date: '', limit: 0, reason: '' });

  const fetchData = async () => {
    try {
      const [defaultRes, dateRes] = await Promise.all([
        axios.get('http://localhost:5000/api/settings/daily-limit'),
        axios.get('http://localhost:5000/api/settings/date-limits')
      ]);
      if (defaultRes.data && defaultRes.data.limit !== undefined) {
        setDefaultLimit(defaultRes.data.limit);
      }
      setDateLimits(dateRes.data || []);
    } catch (err) {
      console.error("Error fetching settings", err);
    }
  };

  useEffect(() => {
    const role = localStorage.getItem('userRole');
    if (role !== 'Admin') { navigate('/'); return; }
    fetchData();
  }, [navigate]);

  const handleUpdateDefault = async (e) => {
    e.preventDefault();
    setIsUpdating(true);
    try {
      const adminId = localStorage.getItem('userId');
      await axios.put('http://localhost:5000/api/settings/daily-limit', { limit: defaultLimit, adminId });
      toast.success('Default limit updated successfully!');
    } catch (err) {
      toast.error('Failed to update default limit.');
    } finally {
      setIsUpdating(false);
    }
  };

  const handleAddException = async (e) => {
    e.preventDefault();
    try {
      const adminId = localStorage.getItem('userId');
      await axios.post('http://localhost:5000/api/settings/date-limits', { 
        ...newException,
        adminId
      });
      toast.success('Date exception added successfully!');
      setNewException({ date: '', limit: 0, reason: '' });
      fetchData();
    } catch (err) {
      toast.error('Failed to add date exception.');
    }
  };

  const handleDeleteException = async (id) => {
    if (!window.confirm("Are you sure you want to delete this exception?")) return;
    try {
      const adminId = localStorage.getItem('userId');
      await axios.delete(`http://localhost:5000/api/settings/date-limits/${id}`, {
        data: { adminId }
      });
      toast.success('Exception removed successfully!');
      fetchData();
    } catch (err) {
      toast.error('Failed to delete exception.');
    }
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif', backgroundColor: '#f8fafc' }}>
      <Toaster position="top-right" />

      <AdminSidebar />

      {/* Main Content Area */}
      <div style={{ flex: 1, padding: '40px' }}>
        <div style={{ marginBottom: '30px' }}>
          <h1 style={{ margin: 0, color: '#0f172a', fontSize: '28px' }}>System Settings</h1>
          <p style={{ color: '#64748b', marginTop: '5px' }}>Configure global rules and daily processing limits for the Barangay Fortune system.</p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '30px', maxWidth: '700px' }}>

          {/* ─── Section 1: Default Daily Limit ─── */}
          <div style={{ background: 'white', padding: '30px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', border: '1px solid #e2e8f0' }}>
            <h3 style={{ margin: '0 0 10px 0', color: '#1e293b', display: 'flex', alignItems: 'center', gap: '8px' }}>
              ⚙️ Default Daily Limit
            </h3>
            <p style={{ color: '#64748b', fontSize: '14px', marginBottom: '25px', lineHeight: '1.5', margin: '0 0 25px 0' }}>
              Set the default maximum number of documents the system can process per day.
              This applies to all standard days unless overridden by a date exception below.
            </p>

            <div style={{ padding: '12px', marginBottom: '25px', borderRadius: '8px', backgroundColor: '#fef2f2', color: '#b91c1c', fontSize: '14px', fontWeight: '600', border: '1px solid #fecaca', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <span>🚫</span> Sunday operations are automatically closed and hidden from residents.
            </div>

            <form onSubmit={handleUpdateDefault} style={{ display: 'flex', alignItems: 'flex-end', gap: '15px' }}>
              <div style={{ flex: 1 }}>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px' }}>DOCUMENTS PER DAY (DEFAULT)</label>
                <input 
                  type="number" 
                  min="1"
                  value={defaultLimit} 
                  onChange={(e) => setDefaultLimit(e.target.value)} 
                  required 
                  style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '18px', fontWeight: 'bold', color: '#0f172a', outline: 'none', boxSizing: 'border-box' }}
                />
              </div>
              <button 
                type="submit" 
                disabled={isUpdating}
                style={{ 
                  padding: '10px 24px', 
                  backgroundColor: isUpdating ? '#94a3b8' : '#2563eb', 
                  color: 'white', border: 'none', borderRadius: '8px', fontSize: '15px', fontWeight: 'bold', 
                  cursor: isUpdating ? 'not-allowed' : 'pointer', whiteSpace: 'nowrap'
                }}
              >
                {isUpdating ? 'Saving...' : 'Save Limit'}
              </button>
            </form>
          </div>

          {/* ─── Section 2: Date-Specific Exceptions ─── */}
          <div style={{ background: 'white', padding: '30px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', border: '1px solid #e2e8f0' }}>
            <h3 style={{ margin: '0 0 10px 0', color: '#1e293b', display: 'flex', alignItems: 'center', gap: '8px' }}>
              📅 Specific Date Exceptions
            </h3>
            <p style={{ color: '#64748b', fontSize: '14px', margin: '0 0 25px 0', lineHeight: '1.5' }}>
              Override the default limit for specific dates — such as holidays, half-days, or special events.
              Setting a limit to <strong>0</strong> means the system is closed for that date.
            </p>

            {/* Add Exception Form */}
            <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '20px', marginBottom: '25px' }}>
              <h4 style={{ margin: '0 0 15px 0', color: '#334155', fontSize: '14px', fontWeight: 'bold' }}>ADD NEW EXCEPTION</h4>
              <form onSubmit={handleAddException} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 2fr auto', gap: '12px', alignItems: 'flex-end' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '11px', fontWeight: 'bold', color: '#64748b', marginBottom: '5px' }}>DATE</label>
                  <input 
                    type="date" 
                    value={newException.date}
                    onChange={(e) => setNewException({...newException, date: e.target.value})}
                    required
                    style={{ width: '100%', padding: '9px', borderRadius: '6px', border: '1px solid #cbd5e1', outline: 'none', boxSizing: 'border-box', fontSize: '13px' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '11px', fontWeight: 'bold', color: '#64748b', marginBottom: '5px' }}>LIMIT (0 = CLOSED)</label>
                  <input 
                    type="number" 
                    min="0"
                    value={newException.limit}
                    onChange={(e) => setNewException({...newException, limit: e.target.value})}
                    required
                    style={{ width: '100%', padding: '9px', borderRadius: '6px', border: '1px solid #cbd5e1', outline: 'none', boxSizing: 'border-box', fontSize: '13px', fontWeight: 'bold' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '11px', fontWeight: 'bold', color: '#64748b', marginBottom: '5px' }}>REASON</label>
                  <input 
                    type="text" 
                    value={newException.reason}
                    onChange={(e) => setNewException({...newException, reason: e.target.value})}
                    required
                    placeholder="e.g. Holiday, Half-Day"
                    style={{ width: '100%', padding: '9px', borderRadius: '6px', border: '1px solid #cbd5e1', outline: 'none', boxSizing: 'border-box', fontSize: '13px' }}
                  />
                </div>
                <button type="submit" style={{ padding: '9px 18px', background: '#10b981', color: 'white', border: 'none', borderRadius: '6px', fontWeight: 'bold', cursor: 'pointer', fontSize: '13px', whiteSpace: 'nowrap' }}>
                  + Add
                </button>
              </form>
            </div>

            {/* Exceptions Table */}
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ background: '#f8fafc', borderBottom: '2px solid #e2e8f0' }}>
                    <th style={{ padding: '12px 16px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>DATE</th>
                    <th style={{ padding: '12px 16px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>LIMIT</th>
                    <th style={{ padding: '12px 16px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>REASON</th>
                    <th style={{ padding: '12px 16px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: 'bold' }}>ACTION</th>
                  </tr>
                </thead>
                <tbody>
                  {dateLimits.length === 0 ? (
                    <tr>
                      <td colSpan="4" style={{ padding: '30px', textAlign: 'center', color: '#94a3b8', fontSize: '14px' }}>No date exceptions configured.</td>
                    </tr>
                  ) : (
                    dateLimits.map((item) => (
                      <tr key={item.id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                        <td style={{ padding: '14px 16px', fontWeight: 'bold', color: '#1e293b', fontSize: '14px' }}>
                          {new Date(item.specific_date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })}
                        </td>
                        <td style={{ padding: '14px 16px', fontSize: '14px' }}>
                          {item.document_limit === 0 
                            ? <span style={{ background: '#fef2f2', color: '#b91c1c', padding: '3px 10px', borderRadius: '4px', fontWeight: 'bold', fontSize: '12px' }}>CLOSED (0)</span>
                            : <span style={{ fontWeight: 'bold', color: '#1e293b' }}>{item.document_limit}</span>
                          }
                        </td>
                        <td style={{ padding: '14px 16px', color: '#475569', fontSize: '14px' }}>{item.reason}</td>
                        <td style={{ padding: '14px 16px' }}>
                          <button 
                            onClick={() => handleDeleteException(item.id)}
                            style={{ padding: '5px 12px', background: '#fef2f2', color: '#b91c1c', border: '1px solid #fecaca', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px' }}
                          >
                            Remove
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
