// client/src/pages/DocumentRecords.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import ReceiptModal from '../components/ReceiptModal';

export default function DocumentRecords() {
  const navigate = useNavigate();
  const staffId = localStorage.getItem('userId');
  
  const [canReview, setCanReview] = useState(localStorage.getItem('canReview') === '1');
  const [records, setRecords] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  
  // FIX: Added the counts state!
  const [counts, setCounts] = useState({ pending: 0, ready: 0 });

  // Receipt Modal State
  const [showReceipt, setShowReceipt] = useState(false);
  const [receiptRequestId, setReceiptRequestId] = useState(null);

  useEffect(() => {
    const fetchDataAndSync = async () => {
      try {
        // 1. Sync permissions silently
        const profileRes = await axios.get(`http://localhost:5000/api/staff/profile/${staffId}`);
        const currentPermission = Number(profileRes.data.can_review) === 1;
        setCanReview(currentPermission);
        localStorage.setItem('canReview', profileRes.data.can_review);

        // 2. Fetch Records Data
        const recordsRes = await axios.get('http://localhost:5000/api/staff/document-records');
        setRecords(recordsRes.data);

        // 3. Fetch Notifications Count
        const requestsRes = await axios.get('http://localhost:5000/api/staff/pending-requests');
        setCounts({
          pending: requestsRes.data.filter(req => req.status === 'Pending').length,
          ready: requestsRes.data.filter(req => req.status === 'Ready to Print').length
        });
      } catch (error) {
        console.error("Failed to fetch data", error);
      }
    };

    fetchDataAndSync();
    const interval = setInterval(fetchDataAndSync, 5000);
    return () => clearInterval(interval);
  }, [staffId]);

  const filteredRecords = records.filter(rec => 
    rec.first_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    rec.last_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    rec.doc_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    rec.request_id.toString().includes(searchTerm)
  );

  const handleLogout = () => {
    localStorage.clear();
    navigate('/');
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', fontFamily: '"Segoe UI", Tahoma, sans-serif', backgroundColor: '#f8fafc', overflowY: 'scroll' }}>
      
      {/* FIX: Added Notification CSS */}
      <style>
        {`
          @keyframes pulse-red {
            0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.7); }
            70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(239, 68, 68, 0); }
            100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); }
          }
          .notification-dot {
            display: inline-flex; align-items: center; justify-content: center;
            background: #ef4444; color: white; border-radius: 50%;
            min-width: 20px; height: 20px; font-size: 11px; font-weight: bold;
            margin-left: 10px; animation: pulse-red 2s infinite;
          }
        `}
      </style>

      <div style={{ width: '280px', background: '#0f172a', color: 'white', padding: '30px 25px', display: 'flex', flexDirection: 'column' }}>
        <h2 style={{ fontSize: '24px', margin: '0 0 15px 0', display: 'flex', alignItems: 'center', gap: '12px' }}>
          👨‍💼 Front Desk System
        </h2>
        <hr style={{ border: '0', borderTop: '1px solid #334155', marginBottom: '40px', width: '100%' }} />
        
        <div style={{ flex: 1 }}>
          <p onClick={() => navigate('/staff-home')} style={{ margin: '25px 0', cursor: 'pointer', fontWeight: 'normal', color: '#94a3b8', display: 'flex', alignItems: 'center' }}>
            🏠 Home Dashboard
          </p>
          
          {canReview && (
            <p onClick={() => navigate('/staff-pending')} style={{ margin: '25px 0', cursor: 'pointer', fontWeight: 'normal', color: '#94a3b8', display: 'flex', alignItems: 'center' }}>
              📋 Pending Review 
              {counts.pending > 0 && <span className="notification-dot">{counts.pending}</span>}
            </p>
          )}

          <p onClick={() => navigate('/staff-ready')} style={{ margin: '25px 0', cursor: 'pointer', fontWeight: 'normal', color: '#94a3b8', display: 'flex', alignItems: 'center' }}>
            🔖 Ready to Print 
            {counts.ready > 0 && <span className="notification-dot">{counts.ready}</span>}
          </p>
          
          <p style={{ margin: '25px 0', cursor: 'default', fontWeight: 'bold', color: 'white', display: 'flex', alignItems: 'center' }}>
            📁 Document Records
          </p>
        </div>
        <button onClick={handleLogout} className="transition-all duration-300 bg-[#334155] text-white hover:bg-red-500 hover:text-white" style={{ padding: '10px', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>Logout</button>
      </div>

      <div style={{ flex: 1, padding: '40px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '30px' }}>
          <div>
            <h1 style={{ margin: '0 0 10px 0', color: '#0f172a', fontSize: '28px' }}>Transaction History</h1>
            <p style={{ color: '#64748b', margin: 0 }}>Search and view all completed or rejected document requests.</p>
          </div>
        </div>

        <div style={{ background: 'white', padding: '20px', borderRadius: '12px', marginBottom: '25px', boxShadow: '0 2px 4px rgba(0,0,0,0.02)', border: '1px solid #e2e8f0' }}>
          <input 
            type="text" 
            placeholder="🔍 Search by resident name, document type, or ID..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{ width: '100%', padding: '12px 16px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', outline: 'none' }}
          />
        </div>

        <div style={{ background: 'white', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: '#f1f5f9', color: '#475569', textAlign: 'left', fontSize: '12px', textTransform: 'uppercase' }}>
                <th style={{ padding: '15px 25px' }}>Date</th>
                <th style={{ padding: '15px 25px' }}>Resident</th>
                <th style={{ padding: '15px 25px' }}>Document Type</th>
                <th style={{ padding: '15px 25px' }}>Status</th>
                <th style={{ padding: '15px 25px' }}>OR Number</th>
                <th style={{ padding: '15px 25px' }}>Processed By</th>
              </tr>
            </thead>
            <tbody>
              {filteredRecords.length > 0 ? filteredRecords.map((rec) => (
                <tr key={rec.request_id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                  <td style={{ padding: '15px 25px', color: '#64748b', fontSize: '14px' }}>{new Date(rec.date_requested).toLocaleDateString()}</td>
                  <td style={{ padding: '15px 25px', fontWeight: '600', color: '#0f172a' }}>{rec.first_name} {rec.last_name}</td>
                  <td style={{ padding: '15px 25px', color: '#1e3a8a', fontWeight: '500' }}>{rec.doc_name}</td>
                  <td style={{ padding: '15px 25px' }}>
                    <span style={{ 
                      padding: '6px 12px', 
                      borderRadius: '20px', 
                      fontSize: '11px', 
                      fontWeight: 'bold',
                      background: rec.status === 'Released' ? '#dcfce7' : '#fee2e2',
                      color: rec.status === 'Released' ? '#166534' : '#991b1b'
                    }}>
                      {rec.status}
                    </span>
                  </td>
                  <td style={{ padding: '15px 25px', color: '#64748b', fontSize: '13px', fontWeight: 'bold' }}>
                    {rec.or_number ? (
                      <button 
                        onClick={() => {
                          setReceiptRequestId(rec.request_id);
                          setShowReceipt(true);
                        }}
                        style={{ padding: '5px 10px', background: '#f0fdf4', color: '#15803d', border: '1px solid #bbf7d0', borderRadius: '6px', cursor: 'pointer', fontSize: '12px', fontWeight: 'bold' }}
                        title="Click to view/print receipt"
                      >
                        📄 {rec.or_number}
                      </button>
                    ) : '-'}
                  </td>
                  <td style={{ padding: '15px 25px', color: '#64748b', fontSize: '13px' }}>ID: #{rec.processed_by || 'N/A'}</td>
                </tr>
              )) : (
                <tr><td colSpan="6" style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>No records found matching your search.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <ReceiptModal 
        isOpen={showReceipt}
        onClose={() => setShowReceipt(false)}
        requestId={receiptRequestId}
        mode="audit"
      />
    </div>
  );
}

// client-vue/src/views/DocumentRecords.vue
<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import axios from 'axios'
import StaffSidebar from '../components/StaffSidebar.vue'
import ReceiptModal from '../components/ReceiptModal.vue'

const records = ref([])
const searchTerm = ref('')
const counts = ref({ pending: 0, ready: 0 })
const canReview = ref(false)

const showReceipt = ref(false)
const receiptRequestId = ref(null)

let interval = null

const fetchDataAndSync = async () => {
  const staffId = localStorage.getItem('userId')
  if (!staffId) return
  
  try {
    const profileRes = await axios.get(`http://localhost:5000/api/staff/profile/${staffId}`)
    const currentPermission = Number(profileRes.data.can_review) === 1
    canReview.value = currentPermission
    localStorage.setItem('canReview', profileRes.data.can_review)

    const recordsRes = await axios.get('http://localhost:5000/api/staff/document-records')
    records.value = recordsRes.data

    const requestsRes = await axios.get('http://localhost:5000/api/staff/pending-requests')
    counts.value = {
      pending: requestsRes.data.filter(req => req.status === 'Pending').length,
      ready: requestsRes.data.filter(req => req.status === 'Ready to Print').length
    }
  } catch (error) {
    console.error("Failed to fetch data", error)
  }
}

onMounted(() => {
  canReview.value = localStorage.getItem('canReview') === '1'
  fetchDataAndSync()
  interval = setInterval(fetchDataAndSync, 5000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})

const filteredRecords = computed(() => {
  if (!searchTerm.value) return records.value
  const term = searchTerm.value.toLowerCase()
  return records.value.filter(rec => 
    (rec.first_name?.toLowerCase().includes(term)) ||
    (rec.last_name?.toLowerCase().includes(term)) ||
    (rec.doc_name?.toLowerCase().includes(term)) ||
    (rec.request_id?.toString().includes(term)) ||
    (rec.or_number?.toLowerCase().includes(term))
  )
})

const openReceipt = (requestId) => {
  receiptRequestId.value = requestId
  showReceipt.value = true
}
</script>

<template>
  <div class="flex h-screen bg-brand-gray font-sans overflow-hidden">
    
    <StaffSidebar activeMenu="Document Records" :counts="counts" :canReview="canReview" />

    <div class="flex-1 p-8 overflow-y-auto">
      <div class="mb-8">
        <h1 class="m-0 text-gray-900 text-3xl font-bold tracking-tight">Transaction History</h1>
        <p class="text-gray-500 mt-1">Search and view all completed or rejected document requests.</p>
      </div>

      <div class="bg-white p-5 rounded-xl mb-6 shadow-sm border border-gray-100">
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
          </div>
          <input 
            type="text" 
            v-model="searchTerm"
            placeholder="Search by resident name, document type, OR number..." 
            class="w-full pl-10 pr-4 py-3 rounded-lg border border-gray-300 outline-none focus:ring-2 focus:ring-brand-blue focus:border-brand-blue transition-colors text-sm"
          />
        </div>
      </div>

      <div class="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
        <table class="w-full text-left border-collapse">
          <thead class="bg-gray-50">
            <tr>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Date</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Resident</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Document Type</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Status</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">OR Number</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Processed By</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="rec in filteredRecords" :key="rec.request_id" class="border-b border-gray-50 hover:bg-gray-50">
              <td class="py-4 px-6 text-gray-500 text-sm">
                {{ new Date(rec.date_requested).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }}
              </td>
              <td class="py-4 px-6 font-bold text-gray-900 text-sm">{{ rec.first_name }} {{ rec.last_name }}</td>
              <td class="py-4 px-6 font-semibold text-brand-blue text-sm">{{ rec.doc_name }}</td>
              <td class="py-4 px-6">
                <span :class="['px-3 py-1.5 rounded-full text-xs font-bold border', rec.status === 'Released' ? 'bg-green-50 text-green-700 border-green-200' : 'bg-red-50 text-red-700 border-red-200']">
                  {{ rec.status }}
                </span>
              </td>
              <td class="py-4 px-6">
                <button 
                  v-if="rec.or_number"
                  @click="openReceipt(rec.request_id)"
                  class="px-3 py-1.5 bg-green-50 text-green-700 border border-green-200 rounded font-bold text-xs hover:bg-green-100 transition-colors flex items-center gap-1"
                  title="Click to view receipt"
                >
                  📄 {{ rec.or_number }}
                </button>
                <span v-else class="text-gray-400 font-bold">-</span>
              </td>
              <td class="py-4 px-6 text-gray-500 text-xs font-mono bg-gray-50/50">
                #{{ rec.processed_by || 'N/A' }}
              </td>
            </tr>
            <tr v-if="filteredRecords.length === 0">
              <td colspan="6" class="p-12 text-center text-gray-400 text-sm font-medium">No records found matching your search.</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <ReceiptModal 
      :isOpen="showReceipt"
      @close="showReceipt = false"
      :requestId="receiptRequestId"
      mode="audit"
    />
  </div>
</template>
