// client/src/pages/Login.jsx
import { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

export default function Login() {
  const [role, setRole] = useState('Resident');
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://localhost:5000/api/auth/login', { role, identifier, password });
      
      const userRole = response.data.role;
      const userId = response.data.id;

      // Store basic auth info
      localStorage.setItem('userId', userId);
      localStorage.setItem('userRole', userRole);

      // Store permissions if they are a staff member
      if (response.data.can_review !== undefined) {
        localStorage.setItem('canReview', response.data.can_review);
      }

      // Navigate based on exact role from backend
      if (userRole === 'Resident') {
          navigate('/resident-dashboard');
      } else if (userRole === 'Staff') {
          navigate('/staff-home');
      } else if (userRole === 'Admin') {
          navigate('/admin-dashboard');
      }
    } catch (err) {
      if (err.response && err.response.data && err.response.data.error) {
        alert(err.response.data.error);
      } else {
        alert("Invalid credentials or server error");
      }
    }
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8fafc', fontFamily: '"Segoe UI", Tahoma, sans-serif' }}>
      <div style={{ background: 'white', padding: '40px 50px', borderRadius: '16px', boxShadow: '0 10px 25px rgba(0,0,0,0.05)', width: '100%', maxWidth: '400px', border: '1px solid #e2e8f0' }}>
        
        <div style={{ textAlign: 'center', marginBottom: '30px' }}>
          <h1 style={{ margin: '0', color: '#0f172a', fontSize: '26px', fontWeight: '800' }}>🏛️ Brgy. Fortune</h1>
          <p style={{ color: '#64748b', margin: '5px 0 0 0', fontSize: '14px', fontWeight: '500' }}>E-Services Portal</p>
        </div>

        <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '600', fontSize: '13px', textTransform: 'uppercase' }}>Account Type</label>
            <select 
              value={role} 
              onChange={(e) => setRole(e.target.value)}
              style={{ width: '100%', padding: '12px 16px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', backgroundColor: '#f8fafc', color: '#0f172a', outline: 'none', cursor: 'pointer' }}
            >
              {/* FIX: Values must exactly match the Database ENUM ('Resident', 'Staff', 'Admin') */}
              <option value="Resident">Resident</option>
              <option value="Staff">Barangay Staff</option>
              <option value="Admin">Administrator</option>
            </select>
          </div>

          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '600', fontSize: '13px', textTransform: 'uppercase' }}>
              {role === 'Resident' ? 'Email Address' : 'Username'}
            </label>
            <input 
              type={role === 'Resident' ? "email" : "text"} 
              placeholder={role === 'Resident' ? 'Enter your email' : 'Enter your username'} 
              value={identifier} 
              onChange={(e) => setIdentifier(e.target.value)} 
              required 
              style={{ width: '100%', padding: '12px 16px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box', outline: 'none' }}
            />
          </div>

          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
              <label style={{ color: '#334155', fontWeight: '600', fontSize: '13px', textTransform: 'uppercase', margin: 0 }}>Password</label>
              {role === 'Resident' && (
                <span onClick={() => navigate('/forgot-password')} style={{ color: '#2563eb', fontSize: '12px', fontWeight: '600', cursor: 'pointer' }}>
                  Forgot Password?
                </span>
              )}
            </div>
            <input 
              type="password" 
              placeholder="Enter your password" 
              value={password} 
              onChange={(e) => setPassword(e.target.value)} 
              required 
              style={{ width: '100%', padding: '12px 16px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box', outline: 'none' }}
            />
          </div>

          <button type="submit" style={{ width: '100%', padding: '14px', backgroundColor: '#2563eb', color: 'white', border: 'none', borderRadius: '8px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer', marginTop: '10px', transition: 'background 0.2s', boxShadow: '0 4px 6px rgba(37, 99, 235, 0.2)' }}>
            Sign In
          </button>
        </form>

        {/* Only show Register link for Residents */}
        {role === 'Resident' && (
          <div style={{ textAlign: 'center', marginTop: '25px', paddingTop: '20px', borderTop: '1px solid #e2e8f0' }}>
            <p style={{ fontSize: '14px', color: '#64748b', margin: 0 }}>
              Don't have an account?{' '}
              <span onClick={() => navigate('/register')} style={{ color: '#2563eb', fontWeight: '600', cursor: 'pointer', textDecoration: 'none' }}>
                Register Here
              </span>
            </p>
          </div>
        )}

      </div>
    </div>
  );
}

// client-vue/src/views/Login.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'

const router = useRouter()
const credentials = ref({
  role: 'Resident',
  identifier: '',
  password: ''
})
const errorMsg = ref('')
const isLoading = ref(false)

const handleLogin = async () => {
  errorMsg.value = ''
  isLoading.value = true
  try {
    const res = await axios.post('http://localhost:5000/api/auth/login', credentials.value)
    const userId = res.data.id || res.data.userId
    
    localStorage.setItem('token', res.data.token)
    localStorage.setItem('userId', userId)
    localStorage.setItem('role', res.data.role) // Vue pages expect 'role'
    localStorage.setItem('userRole', res.data.role) // For backwards compatibility
    localStorage.setItem('firstName', res.data.firstName || '')
    localStorage.setItem('residentId', res.data.residentId || '')
    
    if (res.data.role === 'Admin') router.push('/admin-dashboard')
    else if (res.data.role === 'Staff') router.push('/staff-home')
    else router.push('/resident-dashboard')
  } catch (err) {
    errorMsg.value = err.response?.data?.error || err.response?.data?.message || 'Login failed. Please try again.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-brand-gray flex items-center justify-center p-4">
    <div class="w-full max-w-md dashboard-card p-8 shadow-md">
      <div class="text-center mb-8">
        <div class="w-16 h-16 bg-brand-blue rounded-2xl mx-auto flex items-center justify-center text-white mb-4 shadow-lg">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
        </div>
        <h2 class="text-2xl font-bold text-gray-800">Welcome Back</h2>
        <p class="text-sm text-gray-500 mt-1">Sign in to access your dashboard</p>
      </div>

      <form @submit.prevent="handleLogin" class="space-y-6">
        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2 uppercase">Account Type</label>
          <select v-model="credentials.role" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue focus:border-brand-blue transition-colors outline-none bg-gray-50 text-gray-900 cursor-pointer">
            <option value="Resident">Resident</option>
            <option value="Staff">Barangay Staff</option>
            <option value="Admin">Administrator</option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2 uppercase">{{ credentials.role === 'Resident' ? 'Email Address' : 'Username' }}</label>
          <input :type="credentials.role === 'Resident' ? 'email' : 'text'" v-model="credentials.identifier" required class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue focus:border-brand-blue transition-colors outline-none bg-gray-50" :placeholder="credentials.role === 'Resident' ? 'Enter your email' : 'Enter your username'" />
        </div>
        <div>
          <div class="flex justify-between items-center mb-2">
            <label class="block text-sm font-semibold text-gray-700 uppercase">Password</label>
            <a v-if="credentials.role === 'Resident'" href="#" @click.prevent="router.push('/forgot-password')" class="text-sm text-brand-blue hover:underline font-medium">Forgot password?</a>
          </div>
          <input type="password" v-model="credentials.password" required class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue focus:border-brand-blue transition-colors outline-none bg-gray-50" placeholder="Enter your password" />
        </div>

        <div v-if="errorMsg" class="p-3 rounded-lg bg-red-50 text-red-600 text-sm border border-red-100 flex items-center gap-2">
           <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
           {{ errorMsg }}
        </div>

        <button type="submit" :disabled="isLoading" class="w-full bg-brand-blue hover:bg-brand-light-blue text-white font-bold py-3 px-4 rounded-lg transition-colors shadow-md disabled:bg-brand-light-blue disabled:cursor-not-allowed">
          {{ isLoading ? 'Signing in...' : 'Sign In' }}
        </button>
      </form>

      <p class="text-center text-sm text-gray-600 mt-8">
        Don't have an account? 
        <a href="#" @click.prevent="router.push('/register')" class="text-brand-blue font-bold hover:underline">Register here</a>
      </p>
    </div>
  </div>
</template>
