// client/src/pages/PrintCertificate.jsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';

export default function PrintCertificate() {
  const { id } = useParams(); 
  const navigate = useNavigate();
  const [docData, setDocData] = useState(null);

  useEffect(() => {
    const fetchDocData = async () => {
      try {
        const response = await axios.get(`http://localhost:5000/api/staff/print-data/${id}`);
        setDocData(response.data);
      } catch (error) {
        console.error("Error fetching document data", error);
        toast.error("Failed to load document data.");
      }
    };
    fetchDocData();
  }, [id]);

  if (!docData) return <div style={{ textAlign: 'center', marginTop: '50px' }}>Loading Document...</div>;

  const handlePrint = async () => {
    try {
      const staffId = localStorage.getItem('userId');
      await axios.put(`http://localhost:5000/api/staff/update-status/${id}`, { 
        status: 'Ready for Pickup', 
        official_id: staffId 
      });
      // Optionally toast here, but we will just print
    } catch (error) {
      console.error("Failed to update status", error);
      toast.error("Failed to update status automatically.");
    }
    window.print(); 
  };

  // NEW: Bulletproof Back Function using Native Browser History
  const handleBack = () => {
    if (window.history.length > 2) {
      window.history.back(); // Forces the actual browser back arrow
    } else {
      navigate('/'); // Failsafe if they opened it in a new tab
    }
  };

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div style={{ background: '#e2e8f0', minHeight: '100vh', padding: '40px 20px', fontFamily: '"Times New Roman", Times, serif' }}>
      
      <style>
        {`
          @media print {
            .no-print { display: none !important; }
            body { background: white !important; }
            .print-container { box-shadow: none !important; padding: 0 !important; margin: 0 !important; }
          }
        `}
      </style>

      <div className="no-print" style={{ maxWidth: '800px', margin: '0 auto 20px auto', display: 'flex', justifyContent: 'space-between', background: 'white', padding: '15px 20px', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>
        {/* FIXED: Using the bulletproof handleBack function */}
        <button onClick={handleBack} style={{ padding: '10px 20px', background: '#64748b', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
          ⬅ Back to Queue
        </button>
        <button onClick={handlePrint} style={{ padding: '10px 20px', background: '#2563eb', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', fontSize: '16px' }}>
          🖨️ Print Official Document
        </button>
      </div>

      {/* The Actual A4 Document Paper */}
      <div className="print-container" style={{ background: 'white', maxWidth: '800px', margin: '0 auto', padding: '80px', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)', minHeight: '1122px', position: 'relative' }}>
        
        <div style={{ textAlign: 'center', marginBottom: '50px' }}>
          <p style={{ margin: 0, fontSize: '16px' }}>Republic of the Philippines</p>
          <p style={{ margin: 0, fontSize: '16px' }}>Province of Bulacan</p>
          <p style={{ margin: 0, fontSize: '16px' }}>Municipality of Baliwag</p>
          <h2 style={{ margin: '15px 0 0 0', fontSize: '24px', textTransform: 'uppercase' }}>BARANGAY FORTUNE</h2>
          <hr style={{ borderTop: '2px solid black', margin: '20px 0' }} />
          <h1 style={{ margin: '30px 0', fontSize: '32px', textTransform: 'uppercase', letterSpacing: '2px', textDecoration: 'underline' }}>
            {docData.doc_name}
          </h1>
        </div>

        <div style={{ fontSize: '18px', lineHeight: '2' }}>
          <p><strong>TO WHOM IT MAY CONCERN:</strong></p>
          <p style={{ textIndent: '40px', textAlign: 'justify' }}>
            This is to certify that <strong>{docData.first_name} {docData.middle_name ? docData.middle_name + ' ' : ''}{docData.last_name}</strong>, 
            of legal age, <strong>{docData.civil_status || 'Single'}</strong>, is a bonafide resident of 
            <strong> {docData.addres_street}</strong>, Barangay Fortune, Baliwag, Bulacan.
          </p>
          <p style={{ textIndent: '40px', textAlign: 'justify' }}>
            Based on the records of this office, the aforementioned individual has no derogatory record 
            and is known to be a person of good moral character in the community.
          </p>
          <p style={{ textIndent: '40px', textAlign: 'justify' }}>
            This certification is being issued upon the request of the interested party for <strong>{docData.purpose || 'whatever legal purpose it may serve'}</strong>.
          </p>
          <p style={{ textIndent: '40px', marginTop: '30px' }}>
            Issued this <strong>{today}</strong> at Barangay Fortune, Baliwag, Bulacan.
          </p>
        </div>

        <div style={{ marginTop: '100px', display: 'flex', justifyContent: 'flex-end' }}>
          <div style={{ textAlign: 'center', width: '300px' }}>
            <div style={{ borderBottom: '1px solid black', height: '40px' }}></div>
            <p style={{ margin: '5px 0 0 0', fontWeight: 'bold', fontSize: '18px' }}>
              {docData.captain_name ? docData.captain_name.toUpperCase() : 'JUAN DELA CRUZ'}
            </p>
            <p style={{ margin: 0, fontSize: '14px' }}>Punong Barangay</p>
          </div>
        </div>

        <div style={{ position: 'absolute', bottom: '80px', left: '80px' }}>
          <p style={{ margin: 0, fontSize: '12px' }}>Fee Paid: ₱{docData.base_fee}</p>
          <p style={{ margin: 0, fontSize: '12px' }}>Not Valid Without Official Dry Seal</p>
        </div>
      </div>
    </div>
  );
}

// client-vue/src/views/PrintCertificate.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import axios from 'axios'
import { useToast } from '../composables/useToast'

const route = useRoute()
const router = useRouter()
const toast = useToast()
const docData = ref(null)
const isLoading = ref(true)

const id = route.params.id
const today = computed(() => {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
})

const fetchDocData = async () => {
  try {
    const response = await axios.get(`http://localhost:5000/api/staff/print-data/${id}`)
    docData.value = response.data
  } catch (error) {
    console.error("Error fetching document data", error)
    toast.error("Failed to load document data.")
  } finally {
    isLoading.value = false
  }
}

onMounted(() => {
  fetchDocData()
})

const handlePrint = async () => {
  try {
    const staffId = localStorage.getItem('userId')
    await axios.put(`http://localhost:5000/api/staff/update-status/${id}`, { 
      status: 'Ready for Pickup', 
      official_id: staffId 
    })
  } catch (error) {
    console.error("Failed to update status", error)
    toast.error("Failed to update status automatically.")
  }
  window.print() 
}

const handleBack = () => {
  if (window.history.length > 2) {
    window.history.back()
  } else {
    router.push('/')
  }
}
</script>

<template>
  <div class="print-page bg-gray-200 min-h-screen py-10 px-5 font-serif">
    
    <div v-if="isLoading" class="text-center mt-12 font-sans font-medium text-gray-500">
      Loading Document...
    </div>

    <template v-else>
      <div class="no-print max-w-[800px] mx-auto mb-5 flex justify-between bg-white px-5 py-4 rounded-lg shadow-sm font-sans">
        <button 
          @click="handleBack" 
          class="px-5 py-2.5 bg-gray-500 hover:bg-gray-600 text-white border-none rounded-md cursor-pointer font-bold transition-colors shadow-sm text-sm"
        >
          ⬅ Back to Queue
        </button>
        <button 
          @click="handlePrint" 
          class="px-5 py-2.5 bg-brand-blue hover:bg-brand-light-blue text-white border-none rounded-md cursor-pointer font-bold text-base transition-colors shadow-sm"
        >
          🖨️ Print Official Document
        </button>
      </div>

      <!-- The Actual A4 Document Paper -->
      <div class="print-container bg-white max-w-[800px] mx-auto p-[80px] shadow-lg min-h-[1122px] relative text-black text-[17px] leading-relaxed">
        
        <div class="text-center mb-[50px]">
          <p class="m-0 text-base">Republic of the Philippines</p>
          <p class="m-0 text-base">Province of Bulacan</p>
          <p class="m-0 text-base">Municipality of Baliwag</p>
          <h2 class="mt-[15px] mb-0 text-2xl uppercase tracking-wide font-bold">BARANGAY FORTUNE</h2>
          <hr class="border-t-[2px] border-black my-[20px]" />
          <h1 class="my-[30px] text-[32px] uppercase tracking-[2px] underline font-bold">
            {{ docData.doc_name }}
          </h1>
        </div>

        <div class="text-[18px] leading-[2]">
          <p><strong>TO WHOM IT MAY CONCERN:</strong></p>
          <p class="indent-[40px] text-justify">
            This is to certify that <strong>{{ docData.first_name }} {{ docData.middle_name ? docData.middle_name + ' ' : '' }}{{ docData.last_name }}</strong>, 
            of legal age, <strong>{{ docData.civil_status || 'Single' }}</strong>, is a bonafide resident of 
            <strong> {{ docData.addres_street }}</strong>, Barangay Fortune, Baliwag, Bulacan.
          </p>
          <p class="indent-[40px] text-justify">
            Based on the records of this office, the aforementioned individual has no derogatory record 
            and is known to be a person of good moral character in the community.
          </p>
          <p class="indent-[40px] text-justify">
            This certification is being issued upon the request of the interested party for <strong>{{ docData.purpose || 'whatever legal purpose it may serve' }}</strong>.
          </p>
          <p class="indent-[40px] mt-[30px]">
            Issued this <strong>{{ today }}</strong> at Barangay Fortune, Baliwag, Bulacan.
          </p>
        </div>

        <div class="mt-[100px] flex justify-end">
          <div class="text-center w-[300px]">
            <div class="border-b border-black h-[40px]"></div>
            <p class="mt-[5px] mb-0 font-bold text-[18px]">
              {{ docData.captain_name ? docData.captain_name.toUpperCase() : 'JUAN DELA CRUZ' }}
            </p>
            <p class="m-0 text-[14px]">Punong Barangay</p>
          </div>
        </div>

        <div class="absolute bottom-[80px] left-[80px]">
          <p class="m-0 text-[12px]">Fee Paid: ₱{{ docData.base_fee }}</p>
          <p class="m-0 text-[12px]">Not Valid Without Official Dry Seal</p>
        </div>
      </div>
    </template>
  </div>
</template>

<style>
@media print {
  @page { margin: 0; size: A4; }
  .no-print { display: none !important; }
  body { background: white !important; margin: 0 !important; }
  .print-page { background: white !important; padding: 0 !important; margin: 0 !important; }
  .print-container { box-shadow: none !important; padding: 40px !important; margin: 0 !important; }
}
</style>
