// client/src/pages/Register.jsx
import { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';

export default function Register() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    firstName: '', lastName: '', middleName: '', dateOfBirth: '', 
    civilStatus: 'Single', address: '', contactNumber: '', email: '', password: ''
  });
  const [idProof, setIdProof] = useState(null);

  const handleChange = (e) => setFormData({ ...formData, [e.target.name]: e.target.value });
  const handleFileChange = (e) => setIdProof(e.target.files[0]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const dataToSend = new FormData();
    for (const key in formData) dataToSend.append(key, formData[key]);
    if (idProof) dataToSend.append('id_proof', idProof);

    const loadingToast = toast.loading('Submitting registration...');
    try {
      await axios.post('http://localhost:5000/api/auth/register', dataToSend, { headers: { 'Content-Type': 'multipart/form-data' } });
      toast.success('Registration successful! It can be up to a week before official email confirmation is sent.', { id: loadingToast, duration: 5000 });
      navigate('/');
    } catch (error) {
      toast.error('Error registering account. Email might already exist.', { id: loadingToast });
    }
  };

  const inputClass = "w-full p-3 rounded-lg border border-slate-300 text-sm outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all";
  const labelClass = "block mb-2 text-slate-700 font-semibold text-xs uppercase tracking-wider";

  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-50 font-sans p-4 md:p-8">
      <div className="bg-white p-8 md:p-10 rounded-lg shadow-xl w-full max-w-2xl border border-slate-200 transform transition-all">
        
        <div className="text-center mb-8">
          <h2 className="m-0 text-blue-900 text-2xl md:text-3xl font-extrabold tracking-tight">Resident Registration</h2>
          <p className="text-slate-500 mt-2 text-sm font-medium">Fill in your official details to access Barangay services.</p>
        </div>

        <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-5">
          
          <div className="col-span-1 md:col-span-2">
            <h3 className="border-b border-slate-200 pb-2 m-0 text-slate-900 text-base font-bold">Personal Information</h3>
          </div>

          <div>
            <label className={labelClass}>First Name</label>
            <input type="text" name="firstName" onChange={handleChange} required className={inputClass} />
          </div>
          <div>
            <label className={labelClass}>Last Name</label>
            <input type="text" name="lastName" onChange={handleChange} required className={inputClass} />
          </div>
          <div>
            <label className={labelClass}>Middle Name</label>
            <input type="text" name="middleName" onChange={handleChange} className={inputClass} />
          </div>
          <div>
            <label className={labelClass}>Date of Birth</label>
            <input type="date" name="dateOfBirth" onChange={handleChange} required className={inputClass} />
          </div>
          <div>
            <label className={labelClass}>Civil Status</label>
            <select name="civilStatus" onChange={handleChange} className={inputClass + " bg-slate-50 cursor-pointer"}>
              <option value="Single">Single</option>
              <option value="Married">Married</option>
              <option value="Widowed">Widowed</option>
            </select>
          </div>
          <div>
            <label className={labelClass}>Contact Number</label>
            <input type="text" name="contactNumber" onChange={handleChange} required className={inputClass} />
          </div>
          
          <div className="col-span-1 md:col-span-2">
            <label className={labelClass}>Complete Street Address</label>
            <input type="text" name="address" onChange={handleChange} required className={inputClass} />
          </div>

          <div className="col-span-1 md:col-span-2 mt-4">
            <h3 className="border-b border-slate-200 pb-2 m-0 text-slate-900 text-base font-bold">Account Security & Verification</h3>
          </div>

          <div className="col-span-1 md:col-span-2">
            <label className={labelClass}>Email Address</label>
            <input type="email" name="email" onChange={handleChange} required className={inputClass} />
          </div>
          <div>
            <label className={labelClass}>Password</label>
            <input type="password" name="password" onChange={handleChange} required className={inputClass} />
          </div>
          <div>
            <label className={labelClass}>Confirm Password</label>
            <input type="password" required className={inputClass} />
          </div>

          <div className="col-span-1 md:col-span-2 bg-slate-50 p-5 rounded-lg border border-dashed border-slate-300 mt-2">
            <label className={labelClass + " text-blue-900"}>Upload Valid ID (Image)</label>
            <p className="text-xs text-slate-500 mt-0 mb-3 font-medium">Please provide a clear picture of your ID for verification purposes.</p>
            <input type="file" accept="image/*" onChange={handleFileChange} required className="w-full text-sm text-slate-600 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 transition-colors" />
          </div>

          <div className="col-span-1 md:col-span-2 mt-4">
            <button type="submit" className="w-full p-3.5 bg-emerald-500 text-white rounded-lg text-base font-bold cursor-pointer shadow-lg shadow-emerald-500/30 hover:bg-emerald-600 hover:shadow-emerald-500/50 hover:-translate-y-0.5 active:translate-y-0 transition-all duration-200">
              Submit Registration
            </button>
          </div>
        </form>

        <div className="text-center mt-6">
          <button onClick={() => navigate('/')} className="bg-transparent border-none text-slate-500 cursor-pointer text-sm font-semibold hover:text-slate-800 transition-colors">
            ← Back to Login
          </button>
        </div>

      </div>
    </div>
  );
}

// client-vue/src/views/Register.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'

const router = useRouter()
const form = ref({
  firstName: '',
  lastName: '',
  middleName: '',
  dateOfBirth: '',
  civilStatus: 'Single',
  contactNumber: '',
  address: '',
  email: '',
  password: '',
  confirmPassword: ''
})
const errorMsg = ref('')
const idPicture = ref(null)

const handleFileChange = (e) => {
  idPicture.value = e.target.files[0]
}

const handleRegister = async () => {
  if (form.value.password !== form.value.confirmPassword) {
    errorMsg.value = "Passwords do not match."
    return
  }
  
  errorMsg.value = ''
  
  const formData = new FormData()
  for (const key in form.value) {
    formData.append(key, form.value[key])
  }
  if (idPicture.value) {
    formData.append('id_proof', idPicture.value)
  }

  try {
    const res = await axios.post('http://localhost:5000/api/auth/register', formData, {
      headers: { 'Content-Type': 'multipart/form-data' }
    })
    
    // Store credentials and auto-login
    localStorage.setItem('token', res.data.token)
    localStorage.setItem('role', 'Resident')
    localStorage.setItem('firstName', form.value.firstName)
    localStorage.setItem('residentId', res.data.residentId)
    
    router.push('/resident-dashboard')
  } catch (err) {
    errorMsg.value = err.response?.data?.message || 'Registration failed.'
  }
}
</script>

<template>
  <div class="min-h-screen bg-brand-gray py-12 px-4 sm:px-6 lg:px-8 flex justify-center">
    <div class="max-w-3xl w-full dashboard-card p-8">
      <div class="text-center mb-8">
        <h2 class="text-3xl font-extrabold text-gray-900">Resident Registration</h2>
        <p class="mt-2 text-sm text-gray-600">Fill in your details to create an account.</p>
      </div>

      <form @submit.prevent="handleRegister" class="space-y-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">First Name</label>
            <input type="text" v-model="form.firstName" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Last Name</label>
            <input type="text" v-model="form.lastName" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Middle Name</label>
            <input type="text" v-model="form.middleName" class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Date of Birth</label>
            <input type="date" v-model="form.dateOfBirth" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Civil Status</label>
            <select v-model="form.civilStatus" class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none bg-white">
              <option value="Single">Single</option>
              <option value="Married">Married</option>
              <option value="Widowed">Widowed</option>
            </select>
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Contact Number</label>
            <input type="text" v-model="form.contactNumber" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div class="md:col-span-2">
            <label class="block text-sm font-semibold text-gray-700 mb-1">Complete Address</label>
            <input type="text" v-model="form.address" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div class="md:col-span-2 mt-4 pt-4 border-t border-gray-200">
            <h3 class="text-lg font-bold text-gray-900 mb-4">Account Security</h3>
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Email Address</label>
            <input type="email" v-model="form.email" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Password</label>
            <input type="password" v-model="form.password" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-1">Confirm Password</label>
            <input type="password" v-model="form.confirmPassword" required class="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue outline-none" />
          </div>
          <div class="md:col-span-2 mt-2 bg-blue-50 p-4 rounded-lg border border-blue-100">
            <label class="block text-sm font-bold text-brand-blue mb-1">Upload Valid ID</label>
            <input type="file" @change="handleFileChange" accept="image/*" required class="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-brand-blue file:text-white hover:file:bg-brand-light-blue cursor-pointer" />
          </div>

          <!-- Mandatory Data Privacy Act Disclosure Box -->
          <div class="md:col-span-2 mt-2 bg-gray-50 border border-gray-200 p-4 rounded-xl">
            <h6 class="font-bold mb-2 text-sm text-gray-800 flex items-center gap-2">
              <svg class="w-5 h-5 text-brand-blue" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
              Data Privacy Notice
            </h6>
            <div class="text-gray-600 text-xs mb-3 leading-relaxed">
              In line with the Data Privacy Act, the Barangay Fortune Management System protects your personal data. By signing up, you agree to let the system securely store and process your profile details. This info is used strictly for official barangay records and document request processing.
            </div>
            <div class="flex items-start gap-2">
              <input type="checkbox" required id="privacyCheck" class="mt-1 w-4 h-4 text-brand-blue bg-white border-gray-300 rounded focus:ring-brand-blue focus:ring-2 cursor-pointer" />
              <label for="privacyCheck" class="text-xs text-gray-700 cursor-pointer select-none leading-relaxed">
                I understand and agree to let Barangay Fortune collect and safely handle my personal information.
              </label>
            </div>
          </div>
        </div>

        <div v-if="errorMsg" class="p-3 rounded-lg bg-red-50 text-red-600 text-sm border border-red-100 flex items-center gap-2">
           <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
           {{ errorMsg }}
        </div>

        <button type="submit" class="w-full bg-brand-blue hover:bg-brand-light-blue text-white font-bold py-3 px-4 rounded-lg transition-colors shadow-md mt-6">
          Submit Registration
        </button>
      </form>
      
      <p class="text-center text-sm text-gray-600 mt-8">
        Already have an account? 
        <a href="#" @click.prevent="router.push('/')" class="text-brand-blue font-bold hover:underline">Sign in here</a>
      </p>
    </div>
  </div>
</template>
