// client/src/pages/ResetPassword.jsx
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useParams, useSearchParams, useNavigate } from 'react-router-dom';

export default function ResetPassword() {
  const { token } = useParams();
  const [searchParams] = useSearchParams();
  const email = searchParams.get('email');
  
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [statusMessage, setStatusMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    if (!token || !email) {
      setStatusMessage({ type: 'error', text: "Invalid or missing password reset link." });
    }
  }, [token, email]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setStatusMessage('');

    if (newPassword !== confirmPassword) {
      setStatusMessage({ type: 'error', text: "Passwords do not match." });
      return;
    }
    if (newPassword.length < 6) {
      setStatusMessage({ type: 'error', text: "Password must be at least 6 characters long." });
      return;
    }

    setIsLoading(true);
    
    try {
      const response = await axios.post('http://localhost:5000/api/auth/reset-password', { 
        email, 
        token, 
        newPassword 
      });
      
      setStatusMessage({ type: 'success', text: response.data.message || "Password updated successfully! Redirecting..." });
      
      // Automatically redirect to login after success
      setTimeout(() => {
        navigate('/');
      }, 3000);
      
    } catch (err) {
      if (err.response && err.response.data && err.response.data.error) {
        setStatusMessage({ type: 'error', text: err.response.data.error });
      } else {
        setStatusMessage({ type: 'error', text: "Failed to reset password. The link might be expired." });
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8fafc', fontFamily: '"Segoe UI", Tahoma, sans-serif' }}>
      <div style={{ background: 'white', padding: '40px 50px', borderRadius: '16px', boxShadow: '0 10px 25px rgba(0,0,0,0.05)', width: '100%', maxWidth: '400px', border: '1px solid #e2e8f0' }}>
        
        <div style={{ textAlign: 'center', marginBottom: '30px' }}>
          <h1 style={{ margin: '0', color: '#0f172a', fontSize: '26px', fontWeight: '800' }}>Create New Password</h1>
          <p style={{ color: '#64748b', margin: '5px 0 0 0', fontSize: '14px', fontWeight: '500' }}>{email ? `For ${email}` : 'Enter your new password below'}</p>
        </div>

        {statusMessage && (
          <div style={{ 
            padding: '12px', 
            marginBottom: '20px', 
            borderRadius: '8px', 
            backgroundColor: statusMessage.type === 'success' ? '#dcfce7' : '#fee2e2', 
            color: statusMessage.type === 'success' ? '#166534' : '#b91c1c',
            fontSize: '14px',
            textAlign: 'center',
            fontWeight: '600'
          }}>
            {statusMessage.text}
          </div>
        )}

        <form onSubmit={handleSubmit} style={{ display: 'flex', gap: '20px' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '600', fontSize: '13px', textTransform: 'uppercase' }}>New Password</label>
            <input 
              type="password" 
              placeholder="Enter new password" 
              value={newPassword} 
              onChange={(e) => setNewPassword(e.target.value)} 
              required 
              style={{ width: '100%', padding: '12px 16px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box', outline: 'none' }}
            />
          </div>

          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: '#334155', fontWeight: '600', fontSize: '13px', textTransform: 'uppercase' }}>Confirm Password</label>
            <input 
              type="password" 
              placeholder="Confirm new password" 
              value={confirmPassword} 
              onChange={(e) => setConfirmPassword(e.target.value)} 
              required 
              style={{ width: '100%', padding: '12px 16px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box', outline: 'none' }}
            />
          </div>

          <button 
            type="submit" 
            disabled={isLoading || !token || !email || statusMessage.type === 'success'}
            style={{ 
              width: '100%', padding: '14px', 
              backgroundColor: (isLoading || !token || !email || statusMessage.type === 'success') ? '#94a3b8' : '#10b981', 
              color: 'white', border: 'none', borderRadius: '8px', fontSize: '16px', fontWeight: 'bold', 
              cursor: (isLoading || !token || !email || statusMessage.type === 'success') ? 'not-allowed' : 'pointer', marginTop: '10px', transition: 'background 0.2s', 
              boxShadow: (isLoading || !token || !email || statusMessage.type === 'success') ? 'none' : '0 4px 6px rgba(16, 185, 129, 0.2)' 
            }}
          >
            {isLoading ? 'Updating...' : 'Save Password'}
          </button>
        </form>

      </div>
    </div>
  );
}

// client-vue/src/views/ResetPassword.vue
<script setup>
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import axios from 'axios'

const router = useRouter()
const route = useRoute()
const password = ref('')
const confirmPassword = ref('')
const isLoading = ref(false)
const errorMsg = ref('')
const successMsg = ref('')

const handleReset = async () => {
  if (password.value !== confirmPassword.value) {
    errorMsg.value = 'Passwords do not match.'
    return
  }

  errorMsg.value = ''
  successMsg.value = ''
  isLoading.value = true

  const token = route.params.token
  const email = route.query.email

  try {
    const res = await axios.post('http://localhost:5000/api/auth/reset-password', {
      email,
      token,
      newPassword: password.value
    })
    successMsg.value = 'Password successfully reset! You can now sign in.'
    setTimeout(() => {
      router.push('/')
    }, 2000)
  } catch (err) {
    errorMsg.value = err.response?.data?.error || err.response?.data?.message || 'Failed to reset password.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-brand-gray flex items-center justify-center p-4">
    <div class="max-w-md w-full bg-white rounded-2xl shadow-xl p-8 border border-gray-100">
      
      <div class="text-center mb-8">
        <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-emerald-50 text-emerald-500 mb-4">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
        </div>
        <h2 class="text-2xl font-extrabold text-gray-900 mb-2">Create New Password</h2>
        <p class="text-sm text-gray-500">Please enter your new password below.</p>
      </div>

      <form @submit.prevent="handleReset" class="space-y-5">
        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2 uppercase">New Password</label>
          <input type="password" v-model="password" required class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue focus:border-brand-blue transition-colors outline-none bg-gray-50" placeholder="Enter new password" />
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2 uppercase">Confirm Password</label>
          <input type="password" v-model="confirmPassword" required class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-brand-blue focus:border-brand-blue transition-colors outline-none bg-gray-50" placeholder="Confirm new password" />
        </div>

        <div v-if="errorMsg" class="p-3 rounded-lg bg-red-50 text-red-600 text-sm border border-red-100 flex items-start gap-2">
           <svg class="w-5 h-5 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
           {{ errorMsg }}
        </div>

        <div v-if="successMsg" class="p-3 rounded-lg bg-emerald-50 text-emerald-700 text-sm border border-emerald-100 flex items-start gap-2">
           <svg class="w-5 h-5 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
           {{ successMsg }}
        </div>

        <button type="submit" :disabled="isLoading" class="w-full bg-brand-blue hover:bg-brand-light-blue text-white font-bold py-3 px-4 rounded-lg transition-colors shadow-md disabled:bg-brand-light-blue disabled:cursor-not-allowed">
          {{ isLoading ? 'Resetting...' : 'Reset Password' }}
        </button>
      </form>
    </div>
  </div>
</template>
