// client/src/pages/ResidentApprovals.jsx
import AdminSidebar from '../components/AdminSidebar';
import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';

export default function ResidentApprovals() {
  const navigate = useNavigate();
  const location = useLocation();
  
  const [pendingResidents, setPendingResidents] = useState([]);
  const [selectedIdImage, setSelectedIdImage] = useState(null);
  const [badgeCounts, setBadgeCounts] = useState({ pending: 0, ready: 0, residentApprovals: 0 });

  useEffect(() => {
    fetchPendingResidents();
  }, []);

  const fetchPendingResidents = async () => {
    try {
      const response = await axios.get('http://localhost:5000/api/admin/pending-residents');
      setPendingResidents(response.data);
    } catch (error) {
      console.error("Failed to fetch pending residents", error);
    }
  };

  useEffect(() => {
    const fetchCounts = async () => {
      try {
        const [requestsRes, residentsRes] = await Promise.all([
            axios.get('http://localhost:5000/api/staff/pending-requests'),
            axios.get('http://localhost:5000/api/admin/pending-residents')
        ]);
        const pending = requestsRes.data.filter(req => req.status === 'Pending').length;
        const ready = requestsRes.data.filter(req => req.status === 'Ready to Print').length;
        const residentApprovals = residentsRes.data.length;
        setBadgeCounts({ pending, ready, residentApprovals });
      } catch (error) {
        console.error("Failed to fetch notification counts", error);
      }
    };
    
    fetchCounts();
    const interval = setInterval(fetchCounts, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleApprove = async (residentId) => {
    try {
      await axios.put(`http://localhost:5000/api/admin/approve-resident/${residentId}`);
      setPendingResidents(prev => prev.filter(r => r.resident_id !== residentId));
      toast.success("Resident approved successfully! An email notification has been sent.");
    } catch (error) {
      console.error(error);
      toast.error("Error approving resident.");
    }
  };

  const handleReject = async (residentId) => {
    const reason = window.prompt("⚠️ REJECT REGISTRATION\nPlease enter the reason for rejection (e.g., Unclear ID, Suspected Duplicate):");
    if (!reason || reason.trim() === "") return;

    try {
      await axios.put(`http://localhost:5000/api/admin/reject-resident/${residentId}`, { reason });
      setPendingResidents(prev => prev.filter(r => r.resident_id !== residentId));
      toast.success("Resident rejected. An email notification has been sent.");
    } catch (error) {
      console.error(error);
      toast.error("Error rejecting resident.");
    }
  };

  const handleLogout = () => {
    localStorage.clear();
    navigate('/');
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif', backgroundColor: '#f8fafc', overflowY: 'scroll' }}>
      
      <style>
        {`
          @keyframes pulse-red {
            0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.7); }
            70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(239, 68, 68, 0); }
            100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); }
          }
          .notification-dot {
            display: inline-flex; align-items: center; justify-content: center;
            background: #ef4444; color: white; border-radius: 50%;
            min-width: 20px; height: 20px; font-size: 11px; font-weight: bold;
            margin-left: 10px; animation: pulse-red 2s infinite;
          }
        `}
      </style>

      {/* Admin Sidebar */}
      <AdminSidebar badgeCounts={badgeCounts} />

      {/* Main Content Area */}
      <div style={{ flex: 1, padding: '40px' }}>
        <h1 style={{ margin: '0 0 30px 0', color: '#0f172a', fontSize: '28px' }}>Resident Registration Approvals</h1>
        <p style={{ color: '#64748b', marginBottom: '30px' }}>Review and verify resident accounts before they can access E-Services.</p>
        
        <div style={{ background: 'white', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: '#f1f5f9', color: '#475569', textAlign: 'left', fontSize: '14px', textTransform: 'uppercase' }}>
                <th style={{ padding: '15px 25px' }}>Name</th>
                <th style={{ padding: '15px 25px' }}>Contact Details</th>
                <th style={{ padding: '15px 25px' }}>Address</th>
                <th style={{ padding: '15px 25px' }}>ID Proof</th>
                <th style={{ padding: '15px 25px', width: '200px' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {pendingResidents.length > 0 ? pendingResidents.map((resident) => (
                <tr key={resident.resident_id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                  <td style={{ padding: '15px 25px' }}>
                    <b>{resident.first_name} {resident.last_name}</b><br/>
                    <span style={{fontSize:'12px', color:'#64748b'}}>DOB: {new Date(resident.date_of_birth).toLocaleDateString()}</span>
                  </td>
                  <td style={{ padding: '15px 25px' }}>
                    <span style={{ display: 'block', fontSize: '14px' }}>{resident.email_address}</span>
                    <span style={{ fontSize: '12px', color: '#64748b' }}>{resident.contact_number}</span>
                  </td>
                  <td style={{ padding: '15px 25px', fontSize: '14px' }}>{resident.addres_street}</td>
                  <td style={{ padding: '15px 25px' }}>
                    {resident.id_proof_image ? (
                        <button onClick={() => setSelectedIdImage(resident.id_proof_image)} style={{ padding: '6px 12px', fontSize: '12px', background: 'white', border: '1px solid #cbd5e1', borderRadius: '4px', cursor: 'pointer' }}>👁️ View ID</button>
                    ) : (
                        <span style={{ fontSize: '12px', color: '#94a3b8' }}>No ID Uploaded</span>
                    )}
                  </td>
                  <td style={{ padding: '15px 25px' }}>
                    <div style={{ display: 'flex', gap: '8px' }}>
                      <button onClick={() => handleApprove(resident.resident_id)} style={{ padding: '8px', background: '#10b981', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', flex: 1 }}>Approve</button>
                      <button onClick={() => handleReject(resident.resident_id)} style={{ padding: '8px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', flex: 1 }}>Reject</button>
                    </div>
                  </td>
                </tr>
              )) : <tr><td colSpan="5" style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>No pending resident registrations.</td></tr>}
            </tbody>
          </table>
        </div>
      </div>

      {/* ID Proof Modal */}
      {selectedIdImage && (
        <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0,0,0,0.85)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 }}>
          <div style={{ background: 'white', padding: '30px', borderRadius: '12px', width: '90%', maxWidth: '800px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #e2e8f0', paddingBottom: '15px', marginBottom: '20px' }}>
              <h2 style={{ margin: 0, color: '#1e293b' }}>Resident ID Proof</h2>
              <button onClick={() => setSelectedIdImage(null)} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>Close Window</button>
            </div>
            <div style={{ background: '#f8fafc', padding: '15px', borderRadius: '8px', border: '1px solid #e2e8f0', display: 'flex', justifyContent: 'center' }}>
              <img src={`http://localhost:5000/${selectedIdImage}`} alt="ID Proof" style={{ width: '100%', maxHeight: '600px', objectFit: 'contain', background: '#fff', border: '1px solid #cbd5e1', borderRadius: '6px' }} />
            </div>
          </div>
        </div>
      )}

    </div>
  );
}

// client-vue/src/views/ResidentApprovals.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
import AdminSidebar from '../components/AdminSidebar.vue'
import { useToast } from '../composables/useToast'

const toast = useToast()

const router = useRouter()
const pendingResidents = ref([])
const selectedIdImage = ref(null)
const badgeCounts = ref({ pending: 0, ready: 0, residentApprovals: 0 })
let interval = null

const fetchPendingResidents = async () => {
  try {
    const response = await axios.get('http://localhost:5000/api/admin/pending-residents')
    pendingResidents.value = response.data
  } catch (error) {
    console.error("Failed to fetch pending residents", error)
  }
}

const fetchCounts = async () => {
  try {
    const [requestsRes, residentsRes] = await Promise.all([
      axios.get('http://localhost:5000/api/staff/pending-requests'),
      axios.get('http://localhost:5000/api/admin/pending-residents')
    ])
    const pending = requestsRes.data.filter(req => req.status === 'Pending').length
    const ready = requestsRes.data.filter(req => req.status === 'Ready to Print').length
    const residentApprovals = residentsRes.data.length
    badgeCounts.value = { pending, ready, residentApprovals }
  } catch (error) {
    console.error("Failed to fetch notification counts", error)
  }
}

onMounted(() => {
  fetchPendingResidents()
  fetchCounts()
  interval = setInterval(fetchCounts, 5000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})

const handleApprove = async (residentId) => {
  try {
    await axios.put(`http://localhost:5000/api/admin/approve-resident/${residentId}`)
    pendingResidents.value = pendingResidents.value.filter(r => r.resident_id !== residentId)
    toast.success("Resident approved successfully! An email notification has been sent.")
    fetchCounts()
  } catch (error) {
    console.error(error)
    toast.error("Error approving resident.")
  }
}

const handleReject = async (residentId) => {
  const reason = window.prompt("⚠️ REJECT REGISTRATION\nPlease enter the reason for rejection (e.g., Unclear ID, Suspected Duplicate):")
  if (!reason || reason.trim() === "") return

  try {
    await axios.put(`http://localhost:5000/api/admin/reject-resident/${residentId}`, { reason })
    pendingResidents.value = pendingResidents.value.filter(r => r.resident_id !== residentId)
    toast.success("Resident rejected. An email notification has been sent.")
    fetchCounts()
  } catch (error) {
    console.error(error)
    toast.error("Error rejecting resident.")
  }
}
</script>

<template>
  <div class="flex h-screen bg-brand-gray font-sans overflow-hidden">
    
    <AdminSidebar activeMenu="Resident Approvals" :badgeCounts="badgeCounts" />

    <div class="flex-1 p-8 overflow-y-auto">
      <div class="mb-8">
        <h1 class="m-0 text-gray-900 text-3xl font-bold">Resident Registration Approvals</h1>
        <p class="text-gray-500 mt-1">Review and verify resident accounts before they can access E-Services.</p>
      </div>
      
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table class="w-full text-left border-collapse">
          <thead>
            <tr class="bg-gray-50 border-b-2 border-gray-200 text-gray-500 text-xs uppercase font-bold tracking-wide">
              <th class="py-4 px-6">Name</th>
              <th class="py-4 px-6">Contact Details</th>
              <th class="py-4 px-6">Address</th>
              <th class="py-4 px-6">ID Proof</th>
              <th class="py-4 px-6 w-[220px]">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="resident in pendingResidents" :key="resident.resident_id" class="border-b border-gray-50 hover:bg-gray-50">
              <td class="py-4 px-6">
                <b class="text-gray-800 text-sm block">{{ resident.first_name }} {{ resident.last_name }}</b>
                <span class="text-[11px] text-gray-500 font-semibold block mt-1">DOB: {{ new Date(resident.date_of_birth).toLocaleDateString() }}</span>
              </td>
              <td class="py-4 px-6">
                <span class="block text-sm text-gray-800 mb-1">{{ resident.email_address }}</span>
                <span class="text-xs text-gray-500 font-medium bg-gray-100 px-2 py-1 rounded">{{ resident.contact_number }}</span>
              </td>
              <td class="py-4 px-6 text-sm text-gray-700 leading-relaxed">{{ resident.addres_street }}</td>
              <td class="py-4 px-6">
                <button 
                  v-if="resident.id_proof_image" 
                  @click="selectedIdImage = resident.id_proof_image"
                  class="px-3 py-1.5 text-xs bg-white text-brand-blue border border-brand-blue rounded font-bold hover:bg-blue-50 transition-colors flex items-center gap-1"
                >
                  👁️ View ID
                </button>
                <span v-else class="text-xs text-gray-400 font-medium italic">No ID Uploaded</span>
              </td>
              <td class="py-4 px-6">
                <div class="flex gap-2">
                  <button 
                    @click="handleApprove(resident.resident_id)"
                    class="flex-1 py-2 bg-emerald-500 hover:bg-emerald-600 text-white font-bold rounded text-xs transition-colors shadow-sm"
                  >
                    Approve
                  </button>
                  <button 
                    @click="handleReject(resident.resident_id)"
                    class="flex-1 py-2 bg-red-500 hover:bg-red-600 text-white font-bold rounded text-xs transition-colors shadow-sm"
                  >
                    Reject
                  </button>
                </div>
              </td>
            </tr>
            <tr v-if="pendingResidents.length === 0">
              <td colspan="5" class="p-12 text-center text-gray-400 text-sm font-medium">No pending resident registrations.</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- ID Proof Modal -->
    <div v-if="selectedIdImage" class="fixed inset-0 bg-black/85 flex justify-center items-center z-[1000]">
      <div class="bg-white p-6 rounded-xl w-[90%] max-w-4xl shadow-2xl">
        <div class="flex justify-between items-center border-b border-gray-200 pb-4 mb-5">
          <h2 class="m-0 text-gray-900 text-xl font-bold">Resident ID Proof</h2>
          <button 
            @click="selectedIdImage = null"
            class="px-4 py-2 bg-red-50 text-red-600 border border-red-200 rounded-lg font-bold hover:bg-red-100 transition-colors text-sm"
          >
            Close Window
          </button>
        </div>
        <div class="bg-gray-50 p-4 rounded-lg border border-gray-200 flex justify-center">
          <img 
            :src="`http://localhost:5000/${selectedIdImage}`" 
            alt="ID Proof" 
            class="w-full max-h-[600px] object-contain bg-white border border-gray-300 rounded shadow-sm"
          />
        </div>
      </div>
    </div>

  </div>
</template>
