// client/src/pages/StaffPendingReview.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';

export default function StaffPendingReview() {
  const navigate = useNavigate();
  const staffId = localStorage.getItem('userId');
  
  // Use state instead of a hardcoded constant so it can update in real-time
  const [canReview, setCanReview] = useState(localStorage.getItem('canReview') === '1');
  const [pendingRequests, setPendingRequests] = useState([]);
  const [selectedFiles, setSelectedFiles] = useState(null); 
  const [counts, setCounts] = useState({ pending: 0, ready: 0 });

  useEffect(() => {
    const fetchRequestsAndSync = async () => {
      try {
        // 1. Check Permissions in the background
        const profileRes = await axios.get(`http://localhost:5000/api/staff/profile/${staffId}`);
        const currentPermission = profileRes.data.can_review === 1;
        setCanReview(currentPermission);
        localStorage.setItem('canReview', profileRes.data.can_review);

        // Security check: Kick them out if access was revoked while they were on this page
        if (!currentPermission) {
          navigate('/staff-home');
          return; 
        }

        // 2. Fetch Queue
        const response = await axios.get('http://localhost:5000/api/staff/pending-requests');
        setPendingRequests(response.data.filter(req => req.status === 'Pending'));
        
        // 3. Fetch Notifications Count
        setCounts({
          pending: response.data.filter(req => req.status === 'Pending').length,
          ready: response.data.filter(req => req.status === 'Waiting for Printing' || req.status === 'Ready for Pickup').length
        });
      } catch (error) {
        console.error("Failed to fetch data", error);
      }
    };

    fetchRequestsAndSync();
    const interval = setInterval(fetchRequestsAndSync, 5000);
    return () => clearInterval(interval);
  }, [staffId, navigate]);

  const handleUpdateStatus = async (requestId, newStatus) => {
    try {
      await axios.put(`http://localhost:5000/api/staff/update-status/${requestId}`, { status: newStatus, official_id: staffId });
      const response = await axios.get('http://localhost:5000/api/staff/pending-requests');
      setPendingRequests(response.data.filter(req => req.status === 'Pending'));
      setCounts({
        pending: response.data.filter(req => req.status === 'Pending').length,
        ready: response.data.filter(req => req.status === 'Waiting for Printing' || req.status === 'Ready for Pickup').length
      });
      toast.success("Request approved successfully!");
    } catch (error) {
      toast.error("Error approving request.");
    }
  };

  const handleReject = async (requestId) => {
    const reason = window.prompt("⚠️ REJECT APPLICATION\nPlease enter the reason for rejection:");
    if (!reason || reason.trim() === "") return;
    try {
      await axios.put(`http://localhost:5000/api/staff/reject/${requestId}`, { official_id: staffId, reason: reason });
      const response = await axios.get('http://localhost:5000/api/staff/pending-requests');
      setPendingRequests(response.data.filter(req => req.status === 'Pending'));
      setCounts({
        pending: response.data.filter(req => req.status === 'Pending').length,
        ready: response.data.filter(req => req.status === 'Waiting for Printing' || req.status === 'Ready for Pickup').length
      });
      toast.success("Request rejected.");
    } catch (error) {
      toast.error("Error rejecting request.");
    }
  };

  const handleLogout = () => {
    localStorage.clear();
    navigate('/');
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', fontFamily: '"Segoe UI", Tahoma, sans-serif', backgroundColor: '#f8fafc', overflowY: 'scroll' }}>
      {/* CSS for the glowing notification dots */}
      <style>
        {`
          @keyframes pulse-red {
            0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.7); }
            70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(239, 68, 68, 0); }
            100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); }
          }
          .notification-dot {
            display: inline-flex; align-items: center; justify-content: center;
            background: #ef4444; color: white; border-radius: 50%;
            min-width: 20px; height: 20px; font-size: 11px; font-weight: bold;
            margin-left: 10px; animation: pulse-red 2s infinite;
          }
        `}
      </style>

      <div style={{ width: '280px', background: '#0f172a', color: 'white', padding: '30px 25px', display: 'flex', flexDirection: 'column' }}>
        <h2 style={{ fontSize: '24px', margin: '0 0 15px 0', display: 'flex', alignItems: 'center', gap: '12px' }}>👨‍💼 Front Desk System</h2>
        <hr style={{ border: '0', borderTop: '1px solid #334155', marginBottom: '40px', width: '100%' }} />
        <div style={{ flex: 1 }}>
          <p onClick={() => navigate('/staff-home')} className="transition-all duration-300 hover:translate-x-2 hover:opacity-80" style={{ margin: '25px 0', cursor: 'pointer', fontWeight: 'normal', color: '#94a3b8', display: 'flex', alignItems: 'center' }}>
            🏠 Home Dashboard
          </p>
          
          <p style={{ margin: '25px 0', cursor: 'default', fontWeight: 'bold', color: 'white', display: 'flex', alignItems: 'center' }}>
            📋 Pending Review 
            {counts.pending > 0 && <span className="notification-dot">{counts.pending}</span>}
          </p>

          <p onClick={() => navigate('/staff-ready')} className="transition-all duration-300 hover:translate-x-2 hover:opacity-80" style={{ margin: '25px 0', cursor: 'pointer', fontWeight: 'normal', color: '#94a3b8', display: 'flex', alignItems: 'center' }}>
            🔖 Ready to Print 
            {counts.ready > 0 && <span className="notification-dot">{counts.ready}</span>}
          </p>
          
          <p onClick={() => navigate('/document-records')} className="transition-all duration-300 hover:translate-x-2 hover:opacity-80" style={{ margin: '25px 0', cursor: 'pointer', fontWeight: 'normal', color: '#94a3b8', display: 'flex', alignItems: 'center' }}>
            📁 Document Records
          </p>
        </div>
        <button onClick={handleLogout} className="transition-all duration-300 bg-[#334155] text-white hover:bg-red-500 hover:text-white" style={{ padding: '10px', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>Logout</button>
      </div>

      <div style={{ flex: 1, padding: '40px' }}>
        <h1 style={{ margin: '0 0 30px 0', color: '#0f172a', fontSize: '28px' }}>Document Validation Queue</h1>
        <div style={{ background: 'white', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: '#f1f5f9', color: '#475569', textAlign: 'left', fontSize: '14px', textTransform: 'uppercase' }}>
                <th style={{ padding: '15px 25px' }}>Q #</th>
                <th style={{ padding: '15px 25px' }}>Resident Name</th>
                <th style={{ padding: '15px 25px' }}>Document & Purpose</th>
                <th style={{ padding: '15px 25px' }}>Review Files</th>
                <th style={{ padding: '15px 25px', width: '200px' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {pendingRequests.length > 0 ? pendingRequests.map((req) => (
                <tr key={req.request_id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                  <td style={{ padding: '15px 25px', fontWeight: 'bold' }}>{req.daily_sequence_no}</td>
                  <td style={{ padding: '15px 25px' }}>{req.first_name} {req.last_name}</td>
                  <td style={{ padding: '15px 25px' }}><b>{req.doc_name}</b><br/><span style={{fontSize:'12px', color:'#64748b'}}>{req.purpose}</span></td>
                  <td style={{ padding: '15px 25px' }}>
                    <button onClick={() => setSelectedFiles({ idImage: req.id_proof_image, reqFile: req.requirement_file })} style={{ padding: '6px 12px', fontSize: '12px', background: 'white', border: '1px solid #cbd5e1', borderRadius: '4px', cursor: 'pointer' }}>👁️ Files</button>
                  </td>
                  <td style={{ padding: '15px 25px' }}>
                    <div style={{ display: 'flex', gap: '8px' }}>
                      <button onClick={() => handleUpdateStatus(req.request_id, 'Waiting for Printing')} style={{ padding: '8px', background: '#3b82f6', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', flex: 1 }}>Approve</button>
                      <button onClick={() => handleReject(req.request_id)} style={{ padding: '8px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', flex: 1 }}>Reject</button>
                    </div>
                  </td>
                </tr>
              )) : <tr><td colSpan="5" style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>No pending applications.</td></tr>}
            </tbody>
          </table>
        </div>
      </div>
      
      {/* Attachments Modal */}
      {selectedFiles && (
        <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0,0,0,0.85)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 }}>
          <div style={{ background: 'white', padding: '30px', borderRadius: '12px', width: '90%', maxWidth: '1000px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #e2e8f0', paddingBottom: '15px', marginBottom: '20px' }}>
              <h2 style={{ margin: 0, color: '#1e293b' }}>Application Review</h2>
              <button onClick={() => setSelectedFiles(null)} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>Close Window</button>
            </div>
            <div style={{ display: 'flex', gap: '30px' }}>
              <div style={{ flex: 1, background: '#f8fafc', padding: '15px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                <h4 style={{ margin: '0 0 15px 0', color: '#475569' }}>1. Registered ID</h4>
                {selectedFiles.idImage ? <img src={`http://localhost:5000/${selectedFiles.idImage}`} alt="ID" style={{ width: '100%', height: '400px', objectFit: 'contain', background: '#fff', border: '1px solid #cbd5e1', borderRadius: '6px' }} /> : <p>No ID.</p>}
              </div>
              <div style={{ flex: 1, background: '#f8fafc', padding: '15px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                <h4 style={{ margin: '0 0 15px 0', color: '#475569' }}>2. Submitted Requirement</h4>
                {selectedFiles.reqFile ? <div><img src={`http://localhost:5000/${selectedFiles.reqFile}`} alt="Req" style={{ width: '100%', height: '360px', objectFit: 'contain', background: '#fff', border: '1px solid #cbd5e1', borderRadius: '6px', marginBottom: '10px' }} /><a href={`http://localhost:5000/${selectedFiles.reqFile}`} target="_blank" rel="noreferrer" style={{ display: 'block', textAlign: 'center', color: '#3b82f6', fontWeight: 'bold', textDecoration: 'none' }}>Open File ↗</a></div> : <p>No requirement.</p>}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// client-vue/src/views/StaffPendingReview.vue
<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
import StaffSidebar from '../components/StaffSidebar.vue'
import AdminSidebar from '../components/AdminSidebar.vue'
import PromptModal from '../components/Modals/PromptModal.vue'
import { useToast } from '../composables/useToast'

const router = useRouter()
const toast = useToast()
const userRole = ref(localStorage.getItem('role') || 'Staff')
const canReview = ref(false)
const pendingRequests = ref([])
const selectedFiles = ref(null)
const counts = ref({ pending: 0, ready: 0 })
const badgeCounts = ref({ pending: 0, ready: 0, residentApprovals: 0 })

const searchQuery = ref('')
const isPromptOpen = ref(false)
const rejectRequestId = ref(null)

let interval = null

const fetchRequestsAndSync = async () => {
  const staffId = localStorage.getItem('userId')
  if (!staffId) return

  try {
    const profileRes = await axios.get(`http://localhost:5000/api/staff/profile/${staffId}`)
    const currentPermission = Number(profileRes.data.can_review) === 1
    canReview.value = currentPermission
    localStorage.setItem('canReview', profileRes.data.can_review)

    if (!currentPermission) {
      router.push('/staff-home')
      return
    }

    const response = await axios.get('http://localhost:5000/api/staff/pending-requests')
    pendingRequests.value = response.data.filter(req => req.status === 'Pending')
    
    counts.value = {
      pending: pendingRequests.value.length,
      ready: response.data.filter(req => req.status === 'Waiting for Printing' || req.status === 'Ready for Pickup').length
    }
  } catch (error) {
    console.error("Failed to fetch data", error)
  }
}

onMounted(() => {
  canReview.value = localStorage.getItem('canReview') === '1'
  fetchRequestsAndSync()
  interval = setInterval(fetchRequestsAndSync, 5000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})

const filteredRequests = computed(() => {
  if (!searchQuery.value) return pendingRequests.value
  const q = searchQuery.value.toLowerCase()
  return pendingRequests.value.filter(req => 
    `${req.first_name} ${req.last_name}`.toLowerCase().includes(q) ||
    req.daily_sequence_no?.toString().includes(q)
  )
})

const handleUpdateStatus = async (requestId, newStatus) => {
  const staffId = localStorage.getItem('userId')
  try {
    await axios.put(`http://localhost:5000/api/staff/update-status/${requestId}`, { status: newStatus, official_id: staffId })
    fetchRequestsAndSync()
    toast.success("Request approved successfully!")
  } catch (error) {
    toast.error("Error approving request.")
  }
}

const promptReject = (requestId) => {
  rejectRequestId.value = requestId
  isPromptOpen.value = true
}

const confirmReject = async (reason) => {
  const staffId = localStorage.getItem('userId')
  
  try {
    await axios.put(`http://localhost:5000/api/staff/reject/${rejectRequestId.value}`, { official_id: staffId, reason: reason })
    fetchRequestsAndSync()
    toast.success("Request rejected.")
    isPromptOpen.value = false
  } catch (error) {
    toast.error("Error rejecting request.")
    isPromptOpen.value = false
  }
}

const isPdf = (filePath) => filePath && filePath.toLowerCase().endsWith('.pdf')
</script>

<template>
  <div class="flex h-screen bg-brand-gray font-sans overflow-hidden">
    
    <AdminSidebar v-if="userRole === 'Admin'" activeMenu="Pending Review" :badgeCounts="badgeCounts" />
    <StaffSidebar v-else activeMenu="Pending Review" :counts="counts" :canReview="canReview" />

    <div class="flex-1 p-8 overflow-y-auto">
      <div class="mb-8 flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 class="m-0 text-gray-900 text-3xl font-bold tracking-tight">Document Validation Queue</h1>
          <p class="text-gray-500 mt-1">Review resident applications and requirements before printing.</p>
        </div>
        
        <div class="w-full md:w-64">
          <input 
            type="text" 
            v-model="searchQuery" 
            placeholder="🔍 Search name or Q#" 
            class="w-full p-2.5 rounded-lg border border-gray-300 text-sm outline-none focus:ring-2 focus:ring-brand-blue shadow-sm"
          />
        </div>
      </div>

      <div class="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
        <table class="w-full text-left border-collapse">
          <thead class="bg-gray-50">
            <tr>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Q #</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Resident Name</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Document & Purpose</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Review Files</th>
              <th class="py-4 px-6 text-gray-500 text-xs uppercase tracking-wide font-bold border-b-2 border-gray-200">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="req in filteredRequests" :key="req.request_id" class="border-b border-gray-50 hover:bg-gray-50">
              <td class="py-4 px-6 font-bold text-brand-blue text-lg">#{{ req.daily_sequence_no }}</td>
              <td class="py-4 px-6 font-bold text-gray-900 text-sm">{{ req.first_name }} {{ req.last_name }}</td>
              <td class="py-4 px-6">
                <b class="text-gray-900 text-sm">{{ req.doc_name }}</b><br/>
                <span class="text-[11px] text-gray-500 font-semibold">{{ req.purpose }}</span>
              </td>
              <td class="py-4 px-6">
                <button 
                  @click="selectedFiles = { idImage: req.id_proof_image, reqFile: req.requirement_file }" 
                  class="px-3 py-1.5 bg-white text-gray-600 border border-gray-300 rounded font-bold text-xs hover:bg-gray-50 transition-colors flex items-center gap-1 shadow-sm cursor-pointer"
                >
                  👁️ Files
                </button>
              </td>
              <td class="py-4 px-6">
                <div class="flex gap-2">
                  <button 
                    @click="handleUpdateStatus(req.request_id, 'Waiting for Printing')" 
                    class="flex-1 py-2 bg-brand-blue hover:bg-brand-light-blue text-white font-bold rounded text-xs transition-colors shadow-sm cursor-pointer"
                  >
                    Approve
                  </button>
                  <button 
                    @click="promptReject(req.request_id)" 
                    class="flex-1 py-2 bg-red-500 hover:bg-red-600 text-white font-bold rounded text-xs transition-colors shadow-sm cursor-pointer"
                  >
                    Reject
                  </button>
                </div>
              </td>
            </tr>
            <tr v-if="filteredRequests.length === 0">
              <td colspan="5" class="p-12 text-center text-gray-400 text-sm font-medium">
                <div v-if="searchQuery">No results found for "{{ searchQuery }}".</div>
                <div v-else>
                  <span class="text-4xl block mb-2 opacity-50 grayscale">📂</span>
                  No pending applications.
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Reject Prompt Modal -->
    <PromptModal 
      :isOpen="isPromptOpen"
      title="Reject Application"
      message="Please enter the reason for rejection:"
      confirmText="Reject Application"
      placeholder="e.g. Invalid ID provided"
      @confirm="confirmReject"
      @cancel="isPromptOpen = false"
    />

    <!-- Attachments Modal -->
    <Transition name="modal">
      <div v-if="selectedFiles" class="fixed inset-0 z-[1000] flex justify-center items-center py-10 px-4">
        <!-- Backdrop -->
        <div class="absolute inset-0 bg-gray-900/50 backdrop-blur-sm" @click="selectedFiles = null"></div>

        <div class="bg-white p-8 rounded-2xl w-full max-w-5xl shadow-2xl relative max-h-[90vh] overflow-y-auto transform transition-all">
          <div class="flex justify-between items-center border-b border-gray-200 pb-5 mb-6 sticky top-0 bg-white z-10">
            <h2 class="m-0 text-gray-900 text-2xl font-bold tracking-tight">Application Review</h2>
            <button 
              @click="selectedFiles = null" 
              class="px-5 py-2.5 bg-red-50 text-red-600 border border-red-200 rounded-lg font-bold hover:bg-red-100 transition-colors text-sm cursor-pointer shadow-sm"
            >
              Close Window
            </button>
          </div>
          <div class="flex gap-8 max-md:flex-col">
            
            <div class="flex-1 bg-gray-50 p-6 rounded-xl border border-gray-200">
              <h4 class="m-0 mb-4 text-gray-600 font-bold uppercase tracking-wide text-xs">1. Registered ID</h4>
              <div class="bg-white p-2 rounded-lg border border-gray-200 h-[400px] flex items-center justify-center relative overflow-hidden">
                <template v-if="selectedFiles.idImage">
                  <embed v-if="isPdf(selectedFiles.idImage)" :src="`http://localhost:5000/${selectedFiles.idImage}`" type="application/pdf" class="w-full h-full rounded" />
                  <img v-else :src="`http://localhost:5000/${selectedFiles.idImage}`" alt="ID" class="w-full h-full object-contain rounded" />
                </template>
                <p v-else class="text-gray-400 italic m-0">No ID provided.</p>
              </div>
            </div>
            
            <div class="flex-1 bg-gray-50 p-6 rounded-xl border border-gray-200">
              <h4 class="m-0 mb-4 text-gray-600 font-bold uppercase tracking-wide text-xs">2. Submitted Requirement</h4>
              <div class="bg-white p-2 rounded-lg border border-gray-200 h-[400px] flex items-center justify-center relative overflow-hidden">
                <template v-if="selectedFiles.reqFile">
                  <embed v-if="isPdf(selectedFiles.reqFile)" :src="`http://localhost:5000/${selectedFiles.reqFile}`" type="application/pdf" class="w-full h-full rounded" />
                  <img v-else :src="`http://localhost:5000/${selectedFiles.reqFile}`" alt="Req" class="w-full h-full object-contain rounded" />
                  
                  <a :href="`http://localhost:5000/${selectedFiles.reqFile}`" target="_blank" rel="noreferrer" class="absolute bottom-4 left-1/2 -translate-x-1/2 bg-white/90 backdrop-blur px-4 py-2 rounded-full text-brand-blue font-bold shadow-md border border-gray-100 hover:bg-white transition-colors text-sm text-center">
                    Open File ↗
                  </a>
                </template>
                <p v-else class="text-gray-400 italic m-0">No requirement provided.</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </Transition>

  </div>
</template>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
.modal-enter-from .transform,
.modal-leave-to .transform {
  transform: scale(0.95);
  opacity: 0;
}
</style>
